#!/bin/bash

ifeq (, $(shell which docker-compose))
  docker_compose=docker compose
else
  docker_compose=docker-compose
endif


function dockercompose {
  # use docker-compose then fallback to new docker compose
  docker-compose  "$@"
  docker compose  "$@"
}

echo "Check dependency graph and fix requirements"

docker_compose run -T --rm web bash -c "pip-compile -q && pip-compile dev-requirements.in"



echo "run Flake8..."

docker_compose run -T --rm web flake8 geotrek
status=$?

if test $status -eq 1
then
  exit $status
else
  echo "Flake8 check is ok..."
fi
