# Generated by Django 3.1.3 on 2020-12-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Practice",
                "verbose_name_plural": "Practices",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SitePractice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Visible sur Geotrek-rando",
                        verbose_name="Publié",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Date de publication",
                    ),
                ),
                (
                    "description_teaser",
                    models.TextField(
                        blank=True,
                        help_text="A brief summary (map pop-ups)",
                        verbose_name="Description teaser",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Complete description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "ambiance",
                    models.TextField(
                        blank=True,
                        help_text="Main attraction and interest",
                        verbose_name="Ambiance",
                    ),
                ),
                (
                    "advice",
                    models.TextField(
                        blank=True,
                        help_text="Risks, danger, best period, ...",
                        verbose_name="Advice",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="Period"
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_practices",
                        to="outdoor.practice",
                        verbose_name="Practice",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_practices",
                        to="outdoor.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practice site",
                "verbose_name_plural": "Practice sites",
            },
        ),
    ]
