# Generated by Django 3.1.4 on 2020-12-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0003_auto_20201214_1408"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="advice",
            field=models.TextField(
                blank=True,
                help_text="Risks, danger, best period, ...",
                verbose_name="Advice",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="ambiance",
            field=models.TextField(
                blank=True,
                help_text="Main attraction and interest",
                verbose_name="Ambiance",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="description_teaser",
            field=models.TextField(
                blank=True,
                help_text="A brief summary (map pop-ups)",
                verbose_name="Description teaser",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="period",
            field=models.CharField(blank=True, max_length=1024, verbose_name="Period"),
        ),
        migrations.AddField(
            model_name="site",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="outdoor.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="publication_date",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Date de publication",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Visible sur Geotrek-rando",
                verbose_name="Publié",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="review",
            field=models.BooleanField(
                default=False, verbose_name="En attente de publication"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="description",
            field=models.TextField(
                blank=True, help_text="Complete description", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(
                help_text="Nom public (changez prudemment)",
                max_length=128,
                verbose_name="Nom",
            ),
        ),
        migrations.DeleteModel(
            name="SitePractice",
        ),
    ]
