# Generated by Django 3.1.4 on 2020-12-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0005_auto_20201217_0940"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "practice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="types",
                        to="outdoor.practice",
                        verbose_name="Practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site type",
                "verbose_name_plural": "Site types",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="site",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="outdoor.sitetype",
                verbose_name="Type",
            ),
        ),
    ]
