# Generated by Django 3.1.5 on 2021-01-22 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0014_auto_20210122_1413"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectors",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="practice",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="practices",
                to="outdoor.sector",
                verbose_name="Sector",
            ),
        ),
    ]
