# Generated by Django 3.1.5 on 2021-01-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0015_auto_20210122_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="pictogram",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="upload",
                verbose_name="Pictogram",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="pictogram",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="upload",
                verbose_name="Pictogram",
            ),
        ),
    ]
