# Generated by Django 3.1.7 on 2021-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0020_auto_20210315_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="orientation",
            field=models.JSONField(
                default=list, blank=True, verbose_name="Orientation"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="wind",
            field=models.JSONField(default=list, blank=True, verbose_name="Wind"),
        ),
    ]
