# Generated by Django 3.1.7 on 2021-03-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0021_auto_20210315_1528"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedCourseChild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_parents",
                        to="outdoor.course",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_children",
                        to="outdoor.course",
                    ),
                ),
            ],
            options={
                "ordering": ("parent__id", "order"),
                "unique_together": {("parent", "child")},
            },
        ),
    ]
