# Generated by Django 3.1.13 on 2021-09-10 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0023_site_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.FloatField(
                blank=True,
                help_text="In hours (1.5 = 1 h 30, 24 = 1 day, 48 = 2 days)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Duration",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="gear",
            field=models.TextField(blank=True, verbose_name="Gear"),
        ),
        migrations.AddField(
            model_name="course",
            name="ratings_description",
            field=models.TextField(blank=True, verbose_name="Ratings description"),
        ),
        migrations.AlterField(
            model_name="sitetype",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="site_types",
                to="outdoor.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "practice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_types",
                        to="outdoor.practice",
                        verbose_name="Practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course type",
                "verbose_name_plural": "Course types",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="outdoor.coursetype",
                verbose_name="Type",
            ),
        ),
    ]
