# Generated by Django 3.1.13 on 2021-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0027_auto_20210121_0943'),
        ('outdoor', '0023_site_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='pois_excluded',
            field=models.ManyToManyField(blank=True, related_name='excluded_sites', to='trekking.POI', verbose_name='Excluded POIs'),
        ),
    ]
