# Generated by Django 3.1.13 on 2021-09-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0027_auto_20210121_0943'),
        ('outdoor', '0024_site_pois_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pois_excluded',
            field=models.ManyToManyField(blank=True, related_name='excluded_courses', to='trekking.POI', verbose_name='Excluded POIs'),
        ),
    ]
