# Generated by Django 3.1.13 on 2021-09-15 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0027_merge_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="ratings_min",
        ),
    ]
