# Generated by Django 3.1.13 on 2021-10-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0029_course_pois_excluded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_courses",
                to="outdoor.site",
                verbose_name="Site",
            ),
        ),
    ]
