# Generated by Django 3.1.13 on 2021-09-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoor', '0028_remove_site_ratings_min'),
        ('outdoor', '0029_course_pois_excluded'),
    ]

    operations = [
    ]
