# Generated by Django 3.1.13 on 2021-10-13 13:05

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0031_course_parent_sites"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="points_reference",
            field=django.contrib.gis.db.models.fields.MultiPointField(
                blank=True,
                null=True,
                spatial_index=False,
                srid=settings.SRID,
                verbose_name="Points of reference",
            ),
        ),
    ]
