# Generated by Django 3.1.13 on 2021-10-22 12:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0032_course_points_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
