# Generated by Django 3.1.13 on 2021-10-22 12:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0034_auto_20211022_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
