# Generated by Django 3.1.14 on 2022-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0036_auto_20220127_1013"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="accessibility",
            field=models.TextField(blank=True, verbose_name="Accessibility"),
        ),
    ]
