# Generated by Django 3.2.18 on 2023-04-07 09:43

import django.db.models.deletion
from django.db import migrations, models

import geotrek.authent.models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0011_alter_userprofile_structure"),
        ("outdoor", "0042_flatten_geometrycollection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="structure",
            field=models.ForeignKey(
                default=geotrek.authent.models.default_structure_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="coursetype",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_types",
                to="outdoor.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practices",
                to="outdoor.sector",
                verbose_name="Sector",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="outdoor.ratingscale",
                verbose_name="Scale",
            ),
        ),
        migrations.AlterField(
            model_name="ratingscale",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating_scales",
                to="outdoor.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="structure",
            field=models.ForeignKey(
                default=geotrek.authent.models.default_structure_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="sitetype",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_types",
                to="outdoor.practice",
                verbose_name="Practice",
            ),
        ),
    ]
