# Generated by Django 3.2.15 on 2022-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoor', '0040_auto_20220909_1327'),
        ('outdoor', '0044_auto_20220922_0946'),
    ]

    operations = [
    ]
