# Generated by Django 4.2.23 on 2025-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0047_alter_course_eid_alter_site_eid"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["tree_id", "lft"], name="outdoor_site_tree_id_lft_idx"
            ),
        ),
    ]
