# Generated by Django 5.2.16 on 2026-07-31 08:19

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outdoor", "0048_site_outdoor_site_tree_id_lft_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="coursetype",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="coursetype",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="ratingscale",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="ratingscale",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="sitetype",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="sitetype",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
    ]
