from .prod import *


LEAFLET_CONFIG['SRID'] = 3857
LEAFLET_CONFIG['TILES'] = [
    (gettext_noop('Scan'), 'http://gpp3-wxs.ign.fr/5l7whtiz6iuh9i76vq1wbln5/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=image/jpeg&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}', '&copy; IGN - GeoPortail'),
    (gettext_noop('Scan Express'), 'http://gpp3-wxs.ign.fr/5l7whtiz6iuh9i76vq1wbln5/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.CLASSIQUE&EXCEPTIONS=image/jpeg&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}', '&copy; IGN - GeoPortail'),
    (gettext_noop('Ortho'), 'http://gpp3-wxs.ign.fr/5l7whtiz6iuh9i76vq1wbln5/geoportail/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS&EXCEPTIONS=image/jpeg&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}', '&copy; IGN - GeoPortail'),
]

MOBILE_TILES_URL = LEAFLET_CONFIG['TILES'][0][1]
MOBILE_TILES_GLOBAL_ZOOMS = range(6, 13)

SPLIT_TREKS_CATEGORIES_BY_PRACTICE = True
HIDE_PUBLISHED_TREKS_IN_TOPOLOGIES = True
TOURISM_INTERSECTION_MARGIN = 2000
ZIP_TOURISTIC_CONTENTS_AS_POI = True

MAPENTITY_CONFIG['MAPENTITY_WEASYPRINT'] = True
