-- 20

DROP FUNCTION IF EXISTS create_relationships_iu() CASCADE;
DROP FUNCTION IF EXISTS cleanup_relationships_d() CASCADE;

-- 30

DROP VIEW IF EXISTS o_v_itineraire CASCADE;
DROP VIEW IF EXISTS v_treks CASCADE;
DROP VIEW IF EXISTS o_v_poi CASCADE;
DROP VIEW IF EXISTS v_pois CASCADE;
DROP VIEW IF EXISTS v_services CASCADE;