# Generated by Django 1.11.14 on 2020-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensitivity", "0016_auto_20200211_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensitivearea",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Insertion date"
            ),
        ),
        migrations.AlterField(
            model_name="sensitivearea",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Update date"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="pictogram",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="upload",
                verbose_name="Pictogram",
            ),
        ),
    ]
