# Generated by Django 3.1.5 on 2021-02-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensitivity", "0020_auto_20210122_1029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensitivearea",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sensitivity.species",
                verbose_name="Species or regulatory area",
            ),
        ),
    ]
