# Generated by Django 3.1.14 on 2022-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensitivity", "0021_auto_20210218_0734"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensitivearea",
            name="provider",
            field=models.CharField(
                blank=True, db_index=True, max_length=1024, verbose_name="Provider"
            ),
        ),
    ]
