# Generated by Django 3.2.15 on 2022-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensitivity', '0022_sensitivearea_provider'),
        ('sensitivity', '0023_auto_20220921_1552'),
    ]

    operations = [
    ]
