# Generated by Django 3.2.15 on 2022-11-17 16:33

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensitivity", "0023_auto_20221110_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensitivearea",
            name="geom_buffered",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, editable=False, null=True, srid=settings.SRID
            ),
        ),
    ]
