# Generated by Django 3.2.16 on 2023-02-09 09:27

from django.db import migrations, models


def gen_name(apps, schema_editor):
    """Populate SensitiveAreas name from Species
    """
    sensitive_area = apps.get_model("sensitivity", 'SensitiveArea')
    for row in sensitive_area.objects.all():
        row.name = row.species.name
        row.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('sensitivity', '0026_alter_sensitivearea_geom_buffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivearea',
            name='name',
            field=models.CharField(default=None, null=True, max_length=250, verbose_name='Name'),
        ),
        migrations.RunPython(gen_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sensitivearea',
            name='name',
            field=models.CharField(default='undefined', max_length=250, verbose_name='Name'),
        ),
    ]
