# Generated by Django 4.2.22 on 2025-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensitivity", "0029_auto_20250611_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensitivearea",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
    ]
