# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20180810_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfrastructure',
            name='publication_date',
            field=models.DateField(blank=True, db_column=b'date_publication', editable=False, null=True, verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='baseinfrastructure',
            name='published',
            field=models.BooleanField(db_column=b'public', default=False, help_text='Online', verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='infrastructuretype',
            name='pictogram',
            field=models.FileField(db_column=b'picto', max_length=512, null=True, upload_to=b'upload', verbose_name='Pictogram'),
        ),
    ]
