# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-03 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181203_1101'),
        ('maintenance', '0003_auto_20181203_1101'),
        ('infrastructure', '0006_auto_20181203_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinfrastructure',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='baseinfrastructure',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='baseinfrastructure',
            name='topo_object',
        ),
        migrations.RemoveField(
            model_name='baseinfrastructure',
            name='type',
        ),
        migrations.DeleteModel(
            name='BaseInfrastructure',
        ),
    ]
