# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_remove_base_infrastructure'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signage',
            table='tmp_signa',
        ),
    ]
