# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-14 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_remove_type_type_signage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='infrastructuretype',
            table='a_b_infrastructure',
        ),
    ]
