# Generated by Django 1.11.20 on 2019-07-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0014_logentry_infrastructure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructure",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                db_column="etat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="infrastructure.InfrastructureCondition",
                verbose_name="Condition",
            ),
        ),
    ]
