# Generated by Django 1.11.14 on 2019-10-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0015_auto_20190716_1410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructurecondition",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructuretype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
    ]
