# Generated by Django 2.0.13 on 2020-04-06 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0018_auto_20200228_1755"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER SEQUENCE a_b_amenagement_id_seq RENAME TO infrastructure_infrastructure_id_seq;"
        ),
        migrations.RunSQL(
            "ALTER SEQUENCE a_b_etat_id_seq RENAME TO infrastructure_infrastructurecondition_id_seq;"
        ),
    ]
