# Generated by Django 2.2.15 on 2020-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0019_auto_20200406_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructure",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Visible on Geotrek-rando",
                verbose_name="Published",
            ),
        ),
    ]
