# Generated by Django 3.1.13 on 2021-07-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_userprofile_language'),
        ('infrastructure', '0022_auto_20210121_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureUsageDifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Label')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Infrastructure Usage Difficulty Levels',
                'verbose_name_plural': 'Infrastructure Usage Difficulty Levels',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='InfrastructureMaintenanceDifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Label')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Infrastructure Maintenance Difficulty Level',
                'verbose_name_plural': 'Infrastructure Maintenance Difficulty Levels',
                'ordering': ('label',),
            },
        ),
    ]
