# Generated by Django 3.1.13 on 2021-07-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0023_auto_20210716_0738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructure",
            name="maintenance_difficulty",
            field=models.ForeignKey(
                blank=True,
                help_text="Danger level of maintenance agents' interventions on infrastructure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="infrastructure.infrastructuremaintenancedifficultylevel",
                verbose_name="Maintenance difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="usage_difficulty",
            field=models.ForeignKey(
                blank=True,
                help_text="Danger level of end users' infrastructure usage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="infrastructure.infrastructureusagedifficultylevel",
                verbose_name="Usage difficulty",
            ),
        ),
    ]
