# Generated by Django 3.1.13 on 2021-09-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0025_auto_20210721_1540"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infrastructuremaintenancedifficultylevel",
            options={
                "ordering": ("label",),
                "verbose_name": "Maintenance difficulty",
                "verbose_name_plural": "Maintenance difficulty levels",
            },
        ),
        migrations.AlterModelOptions(
            name="infrastructureusagedifficultylevel",
            options={
                "ordering": ("label",),
                "verbose_name": "Usage difficulty",
                "verbose_name_plural": "Usage difficulty levels",
            },
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="maintenance_difficulty",
            field=models.ForeignKey(
                blank=True,
                help_text="Danger level of infrastructure maintenance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="infrastructures_set",
                to="infrastructure.infrastructuremaintenancedifficultylevel",
                verbose_name="Maintenance difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infrastructures",
                to="infrastructure.infrastructuretype",
                verbose_name="Type",
            ),
        ),
    ]
