# Generated by Django 3.1.14 on 2022-03-14 14:29

from django.conf import settings
from django.db import migrations


def forward(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for lang in settings.MODELTRANSLATION_LANGUAGES:
            cursor.execute(
                f"ALTER TABLE infrastructure_infrastructure ALTER COLUMN published_{lang.replace('-', '_')} SET DEFAULT FALSE;"
            )


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0029_auto_20220314_0912'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
