# Generated by Django 3.2.15 on 2022-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0031_infrastructure_provider'),
        ('infrastructure', '0032_auto_20220921_1547'),
    ]

    operations = [
    ]
