# Generated by Django 3.2.18 on 2023-04-07 09:43

from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0011_alter_userprofile_structure'),
        ('infrastructure', '0032_auto_20221110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.infrastructurecondition', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintenance_difficulty',
            field=models.ForeignKey(blank=True, help_text='Danger level of infrastructure maintenance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infrastructures_set', to='infrastructure.infrastructuremaintenancedifficultylevel', verbose_name='Maintenance difficulty'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='structure',
            field=models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.PROTECT, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infrastructures', to='infrastructure.infrastructuretype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='usage_difficulty',
            field=models.ForeignKey(blank=True, help_text="Danger level of end users' infrastructure usage", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infrastructures_set', to='infrastructure.infrastructureusagedifficultylevel', verbose_name='Usage difficulty'),
        ),
        migrations.AlterField(
            model_name='infrastructurecondition',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='infrastructuremaintenancedifficultylevel',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='infrastructuretype',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='infrastructureusagedifficultylevel',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authent.structure', verbose_name='Related structure'),
        ),
    ]
