# Generated by Django 3.2.19 on 2023-06-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0034_auto_20230503_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureAccessMean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Access mean',
                'verbose_name_plural': 'Access means',
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.infrastructureaccessmean', verbose_name='Access mean'),
        ),
    ]
