# Generated by Django 3.2.21 on 2023-12-04 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0036_infrastructure_access_tmp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructure",
            name="access",
        ),
    ]
