# Generated by Django 4.2.21 on 2025-06-11 08:44

import django.db.models.deletion
from django.db import migrations, models


def forward_fill_provider(apps, schema_editor):
    provider_model = apps.get_model("common", "Provider")

    models = ["Infrastructure"]
    for model_name in models:
        model = apps.get_model("infrastructure", model_name)

        for obj in model.objects.all():
            if obj.provider:
                provider, _ = provider_model.objects.get_or_create(name=obj.provider)
                obj.provider_fk = provider
                obj.save()


def backward_fill_provider(apps, schema_editor):
    models = ["Infrastructure"]
    for model_name in models:
        model = apps.get_model("infrastructure", model_name)

        for obj in model.objects.all():
            if obj.provider_fk:
                obj.provider = obj.provider_fk.name
                obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_provider"),
        ("infrastructure", "0041_alter_infrastructure_eid"),
    ]

    operations = [
        # add a new fk field for provider
        migrations.AddField(
            model_name="infrastructure",
            name="provider_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.provider",
                verbose_name="Provider",
            ),
        ),
        # Populate provider_fk field with provider values
        migrations.RunPython(forward_fill_provider, backward_fill_provider),
        # Delete provider field
        migrations.RemoveField(model_name="infrastructure", name="provider"),
        # Rename provider_fk field
        migrations.RenameField(
            model_name="infrastructure", old_name="provider_fk", new_name="provider"
        ),
    ]
