# Generated by Django 3.2.24 on 2024-03-08 11:23

from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models
import mapentity.models


class Migration(migrations.Migration):
    replaces = [
        ("infrastructure", "0001_initial"),
        ("infrastructure", "0002_auto_20180608_1236"),
        ("infrastructure", "0003_auto_20180810_1753"),
        ("infrastructure", "0004_auto_20181113_1626"),
        ("infrastructure", "0005_baseinfrastructure_eid"),
        ("infrastructure", "0006_auto_20181219_1524"),
        ("infrastructure", "0007_create_infra_signa"),
        ("infrastructure", "0008_create_infrastructure_by_type"),
        ("infrastructure", "0009_remove_base_infrastructure"),
        ("infrastructure", "0010_remove_old_signage"),
        ("infrastructure", "0011_remove_type_type_signage"),
        ("infrastructure", "0012_remove_signagetype_rename_infrastructure_type"),
        ("infrastructure", "0013_attachments_infrastructure"),
        ("infrastructure", "0014_logentry_infrastructure"),
        ("infrastructure", "0015_auto_20190716_1410"),
        ("infrastructure", "0016_auto_20191029_1110"),
        ("infrastructure", "0017_auto_20200211_1011"),
        ("infrastructure", "0018_auto_20200228_1755"),
        ("infrastructure", "0019_auto_20200406_1332"),
        ("infrastructure", "0020_auto_20200831_1406"),
        ("infrastructure", "0021_auto_20201117_1302"),
        ("infrastructure", "0022_auto_20210121_0943"),
        ("infrastructure", "0023_auto_20210716_0738"),
        ("infrastructure", "0024_auto_20210716_1043"),
        ("infrastructure", "0025_auto_20210721_1540"),
        ("infrastructure", "0026_auto_20210908_1337"),
        ("infrastructure", "0027_infrastructure_accessibility"),
        ("infrastructure", "0028_infrastructure_published_translation"),
        ("infrastructure", "0029_auto_20220314_0912"),
        ("infrastructure", "0030_auto_20220314_1429"),
        ("infrastructure", "0031_infrastructure_provider"),
        ("infrastructure", "0032_auto_20221110_1128"),
        ("infrastructure", "0033_auto_20230407_0943"),
        ("infrastructure", "0034_auto_20230503_0837"),
        ("infrastructure", "0035_auto_20230613_0917"),
        ("infrastructure", "0036_infrastructure_access_tmp"),
        ("infrastructure", "0037_remove_infrastructure_access"),
        ("infrastructure", "0038_rename_access_tmp_infrastructure_access"),
    ]
    initial = True

    dependencies = [
        ("common", "0100_initial"),
        ("authent", "0100_initial"),
        ("core", "0100_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfrastructureAccessMean",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                ("label", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Access mean",
                "verbose_name_plural": "Access means",
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="InfrastructureUsageDifficultyLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=250, unique=True, verbose_name="Label"),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage difficulty",
                "verbose_name_plural": "Usage difficulty levels",
                "ordering": ("label",),
                "unique_together": {("label", "structure")},
            },
        ),
        migrations.CreateModel(
            name="InfrastructureType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                (
                    "pictogram",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="upload",
                        verbose_name="Pictogram",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[("A", "Building"), ("E", "Facility")], max_length=1
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infrastructure Type",
                "verbose_name_plural": "Infrastructure Types",
                "ordering": ["label", "type"],
            },
        ),
        migrations.CreateModel(
            name="InfrastructureMaintenanceDifficultyLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                ("label", models.CharField(max_length=250, verbose_name="Label")),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance difficulty",
                "verbose_name_plural": "Maintenance difficulty levels",
                "ordering": ("label",),
                "unique_together": {("label", "structure")},
            },
        ),
        migrations.CreateModel(
            name="InfrastructureCondition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                ("label", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infrastructure Condition",
                "verbose_name_plural": "Infrastructure Conditions",
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Visible on Geotrek-rando",
                        verbose_name="Published",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Publication date",
                    ),
                ),
                (
                    "topo_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.topology",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Reference, code, ...",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Specificites", verbose_name="Description"
                    ),
                ),
                (
                    "implantation_year",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Implantation year"
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="External id",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=1024,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "accessibility",
                    models.TextField(blank=True, verbose_name="Accessibility"),
                ),
                (
                    "access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.accessmean",
                        verbose_name="Access mean",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="infrastructure.infrastructurecondition",
                        verbose_name="Condition",
                    ),
                ),
                (
                    "maintenance_difficulty",
                    models.ForeignKey(
                        blank=True,
                        help_text="Danger level of infrastructure maintenance",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="infrastructures_set",
                        to="infrastructure.infrastructuremaintenancedifficultylevel",
                        verbose_name="Maintenance difficulty",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        default=geotrek.authent.models.default_structure_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="infrastructures",
                        to="infrastructure.infrastructuretype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "usage_difficulty",
                    models.ForeignKey(
                        blank=True,
                        help_text="Danger level of end users' infrastructure usage",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="infrastructures_set",
                        to="infrastructure.infrastructureusagedifficultylevel",
                        verbose_name="Usage difficulty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infrastructure",
                "verbose_name_plural": "Infrastructures",
            },
            bases=("core.topology", mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
