#!/usr/bin/python3

import os

from setuptools import find_packages, setup

here = os.path.abspath(os.path.dirname(__file__))


setup(
    name="geotrek",
    version=open(os.path.join(here, "VERSION")).read().strip(),
    author="Makina Corpus",
    author_email="geobi@makina-corpus.com",
    url="https://makina-corpus.com",
    description="Geotrek",
    scripts=["manage.py"],
    install_requires=[
        "Django==5.2.*",
        "mapentity@git+https://github.com/makinacorpus/django-mapentity@multiple_geometries#egg=mapentity",
        "chardet",
        "cairosvg",
        "cairocffi",
        "python-dotenv",
        "pymemcache",
        "coreschema",
        "coreapi",
        "django-autocomplete-light",
        "psycopg2",
        "pdfimpose",
        "Pillow",
        "simplekml",
        "pygal",
        "paperclip",
        "django-modelcluster",
        "django-mptt",
        "geojson",
        "tif2geojson",
        "drf-dynamic-fields",
        "drf-yasg",
        "xlrd",
        "landez",
        "large-image-source-vips",
        "django-large-image",
        "celery",
        "redis",
        "django-celery-results",
        "drf-extensions",
        "django-colorfield",
        "Fiona",
        "markdown",
        "weasyprint",
        "django-weasyprint",
        "django-clearcache",
        "pyopenair",
        "django-treebeard",
        "easy-thumbnails[svg]",
        "django-maintenance-mode",
        "django-flask-authent-backend@git+https://github.com/PnX-SI/django-flask-authent-backend@main#egg=django-flask-authent-backend",
        # prod,
        "gunicorn[gevent]",
        "sentry-sdk",
        "django-embed_video@git+https://github.com/jazzband/django-embed-video.git@master#egg=django-embed-video",  # wait for 1.4.11 release ...
    ],
    include_package_data=True,
    license="BSD, see LICENSE file.",
    packages=find_packages(),
    classifiers=[
        "Natural Language :: English",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Development Status :: 5 - Production/Stable",
        "Programming Language :: Python :: 3",
    ],
)
