#!/usr/bin/python3

import os

from setuptools import setup, find_packages

here = os.path.abspath(os.path.dirname(__file__))


setup(
    name='geotrek',
    version=open(os.path.join(here, 'VERSION')).read().strip(),
    author='Makina Corpus',
    author_email='geobi@makina-corpus.com',
    url='https://makina-corpus.com',
    description="Geotrek",
    scripts=['manage.py'],
    install_requires=[
        'Django==4.2.*',
        'mapentity',
        'chardet',
        'cairosvg',
        'cairocffi',
        'python-dotenv',
        'pymemcache',
        'coreschema',
        'coreapi',
        'psycopg2',
        'pdfimpose',
        'docutils',
        'Pillow',
        'simplekml',
        'pygal',
        'paperclip',
        'django-modelcluster',
        'django-mptt',
        'geojson',
        'tif2geojson',
        'drf-dynamic-fields',
        'drf-yasg',
        'xlrd',
        'landez',
        'large-image-source-vips',
        'django-large-image',
        'celery',
        'redis',
        'django-celery-results',
        'drf-extensions',
        'django-colorfield',
        'Fiona',
        'markdown',
        "weasyprint",
        'django-weasyprint',
        "django-clearcache",
        "pyopenair",
        "django-treebeard",
        'easy-thumbnails[svg]',
        # prod,
        'gunicorn[gevent]',
        'sentry-sdk',
    ],
    include_package_data=True,
    license='BSD, see LICENSE file.',
    packages=find_packages(),
    classifiers=['Natural Language :: English',
                 'Environment :: Web Environment',
                 'Framework :: Django',
                 'Development Status :: 5 - Production/Stable',
                 'Programming Language :: Python :: 3'],
)
