from unittest import TestCase


# TODO
class PointTopologyParserMixinTest(TestCase):
    def test_start_succeeds_with_path_without_dynamic_segmentation(self): ...

    def test_start_succeeds_without_path_without_dynamic_segmentation(self): ...

    def test_start_succeeds_with_path_with_dynamic_segmentation(self): ...

    def test_start_fails_without_path_with_dynamic_segmentation(self): ...

    def test_parsing_fails_when_geom_is_not_a_point(self): ...

    def test_parsing_succeeds_when_geom_is_a_point_several_objects(self): ...
