services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/runner/work/Geotrek-admin/Geotrek-admin/cypress/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/runner/work/Geotrek-admin/Geotrek-admin/var:/var/www/geotrek
    depends_on:
      - web
      - api