# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cirkwi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cirkwilocomotion",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Cirkwi name"),
        ),
        migrations.AlterField(
            model_name="cirkwipoicategory",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Cirkwi name"),
        ),
        migrations.AlterField(
            model_name="cirkwitag",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Cirkwi name"),
        ),
        migrations.AlterModelTable(
            name="cirkwilocomotion",
            table=None,
        ),
        migrations.AlterModelTable(
            name="cirkwipoicategory",
            table=None,
        ),
        migrations.AlterModelTable(
            name="cirkwitag",
            table=None,
        ),
    ]
