# Generated by Django 3.2.24 on 2024-03-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("cirkwi", "0001_initial"),
        ("cirkwi", "0002_auto_20200211_1011"),
        ("cirkwi", "0003_auto_20200406_1353"),
    ]
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CirkwiLocomotion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField(unique=True, verbose_name="Cirkwi id")),
                ("name", models.CharField(max_length=128, verbose_name="Cirkwi name")),
            ],
            options={
                "verbose_name": "Cirkwi locomotion",
                "verbose_name_plural": "Cirkwi locomotions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CirkwiPOICategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField(unique=True, verbose_name="Cirkwi id")),
                ("name", models.CharField(max_length=128, verbose_name="Cirkwi name")),
            ],
            options={
                "verbose_name": "Cirkwi POI category",
                "verbose_name_plural": "Cirkwi POI categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CirkwiTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField(unique=True, verbose_name="Cirkwi id")),
                ("name", models.CharField(max_length=128, verbose_name="Cirkwi name")),
            ],
            options={
                "verbose_name": "Cirkwi tag",
                "verbose_name_plural": "Cirkwi tags",
                "ordering": ["name"],
            },
        ),
    ]
