# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 16:14
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def add_permissions_signage(apps, schema_editor):
    call_command('update_geotrek_permissions', verbosity=0)
    UserModel = apps.get_model('auth', 'User')
    GroupModel = apps.get_model('auth', 'Group')
    PermissionModel = apps.get_model('auth', 'Permission')
    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    type_permissions = ['add', 'change', 'change_geom', 'delete', 'export', 'read']
    content_type_signage = ContentTypeModel.objects.get(model='signage')
    for user in UserModel.objects.all():
        for type_perm in type_permissions:
            if user.user_permissions.filter(codename='%s_signage' % type_perm).exists():
                user.user_permissions.add(PermissionModel.objects.get(
                    codename='%s_signage' % type_perm, content_type=content_type_signage))
    for group in GroupModel.objects.all():
        for type_perm in type_permissions:
            if group.permissions.filter(codename='%s_signage' % type_perm).exists():
                group.permissions.add(PermissionModel.objects.get(
                    codename='%s_signage' % type_perm, content_type=content_type_signage))


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_remove_signage_old_type'),
        ('authent', '0003_auto_20181203_1518'),
    ]

    operations = [
        migrations.RunPython(add_permissions_signage)
    ]
