# Generated by Django 3.1.14 on 2022-01-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0005_remove_userprofile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="name",
            field=models.CharField(db_index=True, max_length=256, verbose_name="Nom"),
        ),
    ]
