# Generated by Django 3.1.13 on 2021-12-29 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0006_selectableuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SelectableUser",
        ),
    ]
