# Generated by Django 3.1.13 on 2022-01-27 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0007_delete_selectableuser"),
        ("authent", "0006_auto_20220127_0944"),
    ]

    operations = []
