# Generated by Django 3.1.14 on 2022-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0008_merge_20220127_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extended_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Extended username'),
        ),
    ]
