# Generated by Django 4.2.23 on 2025-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0011_alter_userprofile_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="osm_token",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="OSM token"
            ),
        ),
    ]
