# Generated by Django 3.2.24 on 2024-03-08 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models


class Migration(migrations.Migration):
    replaces = [
        ("authent", "0001_initial"),
        ("authent", "0002_auto_20181107_1620"),
        ("authent", "0003_auto_20181203_1518"),
        ("authent", "0004_auto_20200211_1011"),
        ("authent", "0005_remove_userprofile_language"),
        ("authent", "0006_auto_20220127_0944"),
        ("authent", "0006_selectableuser"),
        ("authent", "0007_delete_selectableuser"),
        ("authent", "0008_merge_20220127_1710"),
        ("authent", "0009_userprofile_extended_username"),
        ("authent", "0010_auto_20221110_1128"),
        ("authent", "0011_alter_userprofile_structure"),
    ]
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=256, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Structure",
                "verbose_name_plural": "Structures",
                "ordering": ["name"],
                "permissions": (("can_bypass_structure", "Can bypass structure"),),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extended_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Extended username",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        default=geotrek.authent.models.default_structure_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User's profile",
                "verbose_name_plural": "User's profiles",
            },
        ),
    ]
