# Generated by Django 1.11.14 on 2019-10-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0005_auto_20190306_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="interventiondisorder",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="interventionjob",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="interventionstatus",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="interventiontype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="projectdomain",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="projecttype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
    ]
