# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20191029_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionstatus',
            options={'ordering': ['order', 'id'], 'verbose_name': "Intervention's status", 'verbose_name_plural': "Intervention's statuses"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', '-begin_year'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='interventionstatus',
            name='order',
            field=models.PositiveSmallIntegerField(db_column='order', default=0, verbose_name='Display order'),
        ),
    ]
