# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0006_auto_20191029_1110"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interventionstatus",
            options={
                "ordering": ["order", "status"],
                "verbose_name": "Intervention's status",
                "verbose_name_plural": "Intervention's statuses",
            },
        ),
        migrations.AddField(
            model_name="interventionstatus",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_column="order",
                default=None,
                null=True,
                verbose_name="Display order",
            ),
        ),
    ]
