# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 09:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0007_auto_20191209_1315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="area",
            field=models.FloatField(
                blank=True,
                db_column="surface",
                default=0,
                editable=False,
                null=True,
                verbose_name="Area",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="height",
            field=models.FloatField(
                blank=True,
                db_column="hauteur",
                default=0.0,
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="heliport_cost",
            field=models.FloatField(
                blank=True,
                db_column="cout_heliport",
                default=0.0,
                null=True,
                verbose_name="Heliport cost",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="material_cost",
            field=models.FloatField(
                blank=True,
                db_column="cout_materiel",
                default=0.0,
                null=True,
                verbose_name="Material cost",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="subcontract_cost",
            field=models.FloatField(
                blank=True,
                db_column="cout_soustraitant",
                default=0.0,
                null=True,
                verbose_name="Subcontract cost",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="width",
            field=models.FloatField(
                blank=True,
                db_column="largeur",
                default=0.0,
                null=True,
                verbose_name="Width",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contractors",
            field=models.ManyToManyField(
                blank=True,
                db_table="m_r_chantier_prestataire",
                related_name="projects",
                to="maintenance.Contractor",
                verbose_name="Contractors",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_year",
            field=models.IntegerField(
                blank=True, db_column="annee_fin", null=True, verbose_name="End year"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="global_cost",
            field=models.FloatField(
                blank=True,
                db_column="cout_global",
                default=0,
                help_text="€",
                null=True,
                verbose_name="Global cost",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                db_column="maitre_ouvrage",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manage",
                to="common.Organism",
                verbose_name="Project manager",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_owner",
            field=models.ForeignKey(
                blank=True,
                db_column="maitre_oeuvre",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="own",
                to="common.Organism",
                verbose_name="Project owner",
            ),
        ),
    ]
