# Generated by Django 1.11.14 on 2020-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0011_auto_20200305_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funding",
            name="amount",
            field=models.FloatField(verbose_name="Amount"),
        ),
    ]
