# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maintenance', '0012_auto_20200311_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='topology',
        ),
        migrations.AddField(
            model_name='intervention',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
