# Generated by Django 3.2.18 on 2023-04-07 09:47

import django.db.models.deletion
from django.db import migrations, models

import geotrek.authent.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0035_auto_20230407_0947"),
        ("common", "0031_auto_20230407_0947"),
        ("authent", "0011_alter_userprofile_structure"),
        ("maintenance", "0019_auto_20220127_1005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="funding",
            name="organism",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="common.organism",
                verbose_name="Organism",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="stake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interventions",
                to="core.stake",
                verbose_name="Stake",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="maintenance.interventionstatus",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="structure",
            field=models.ForeignKey(
                default=geotrek.authent.models.default_structure_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="target_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maintenance.interventiontype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="interventiondisorder",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="interventionjob",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="interventionstatus",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="interventiontype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maintenance.projectdomain",
                verbose_name="Domain",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manage",
                to="common.organism",
                verbose_name="Project manager",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="own",
                to="common.organism",
                verbose_name="Project owner",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="structure",
            field=models.ForeignKey(
                default=geotrek.authent.models.default_structure_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maintenance.projecttype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="projectdomain",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="projecttype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
    ]
