# Generated by Django 3.2.18 on 2023-04-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maintenance', '0020_auto_20230407_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='target_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='manday',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.interventionjob', verbose_name='Job'),
        ),
    ]
