# Generated by Django 3.2.21 on 2023-12-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_auto_20231206_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='date',
        ),
    ]
