# Generated by Django 3.2.23 on 2024-02-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_intervention_contractors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='workforce_cost',
        ),
    ]
