# Generated by Django 5.2.12 on 2026-04-10 10:03

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0029_remove_intervention_workforce_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                editable=False, null=True, srid=settings.SRID
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                editable=False, null=True, srid=settings.SRID
            ),
        ),
    ]
