# Generated by Django 5.2.12 on 2026-05-21 11:37

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0030_intervention_geom_project_geom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervention",
            name="area",
        ),
        migrations.RunSQL(
            """
            DROP FUNCTION IF EXISTS update_area_intervention();
            DROP TRIGGER IF EXISTS maintenance_intervention_area_iu_tgr ON maintenance_intervention;
            """
        ),
        migrations.AddField(
            model_name="intervention",
            name="area",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("width"), "*", models.F("length")
                ),
                output_field=models.FloatField(),
                verbose_name="Area",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="intervention",
            name="height",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Height"),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="width",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Width"),
        ),
    ]
