# Generated by Django 5.2.12 on 2026-05-22 07:32

from django.db import migrations


def update_geom(apps, schema_editor):
    Intervention = apps.get_model("maintenance", "Intervention")
    ContentType = apps.get_model("contenttypes", "ContentType")

    target_types = Intervention.objects.values_list(
        "target_type_id", flat=True
    ).distinct()

    for type_id in target_types:
        if not type_id:
            continue

        ct = ContentType.objects.get(pk=type_id)
        try:
            TargetModel = apps.get_model(ct.app_label, ct.model)
        except LookupError:
            continue

        type_interventions = Intervention.objects.filter(target_type_id=type_id)

        target_ids = type_interventions.values_list("target_id", flat=True).distinct()
        target_dict = TargetModel.objects.filter(id__in=target_ids).in_bulk()

        for intervention in type_interventions:
            target = target_dict.get(intervention.target_id)
            if target and hasattr(target_dict, "geom"):
                intervention.geom = target_dict.geom
                intervention.save(update_fields=["geom"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "maintenance",
            "0031_alter_intervention_area_alter_intervention_height_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS maintenance_intervention_area_iu_tgr ON maintenance_intervention;
            DROP FUNCTION IF EXISTS update_area_intervention();
            """
        ),
        migrations.RunPython(update_geom, reverse_code=migrations.RunPython.noop),
    ]
