# Generated by Django 3.1.13 on 2021-10-22 12:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0015_auto_20210121_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristiccontent",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="touristicevent",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
