# Generated by Django 3.1.14 on 2022-01-27 09:19

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0018_auto_20211022_1255"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="informationdesk",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom"], name="informationdesk_geom_gist_idx"
            ),
        ),
    ]
