# Generated by Django 3.1.14 on 2022-02-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0019_auto_20220127_1019"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelAccessibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pictogram",
                    models.FileField(
                        max_length=512,
                        null=True,
                        upload_to="upload",
                        verbose_name="Pictogram",
                    ),
                ),
                ("label", models.CharField(max_length=128, verbose_name="Label")),
            ],
            options={
                "verbose_name": "Label accessibility",
                "verbose_name_plural": "Labels accessibility",
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="informationdesk",
            name="accessibility",
            field=models.TextField(blank=True, verbose_name="Accessibility"),
        ),
        migrations.AddField(
            model_name="touristiccontent",
            name="accessibility",
            field=models.TextField(blank=True, verbose_name="Accessibility"),
        ),
        migrations.AlterField(
            model_name="touristicevent",
            name="accessibility",
            field=models.TextField(blank=True, verbose_name="Accessibility"),
        ),
        migrations.AddField(
            model_name="informationdesk",
            name="label_accessibility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="desks",
                to="tourism.labelaccessibility",
                verbose_name="Label accessibility",
            ),
        ),
        migrations.AddField(
            model_name="touristiccontent",
            name="label_accessibility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="tourism.labelaccessibility",
                verbose_name="Label accessibility",
            ),
        ),
    ]
