# Generated by Django 3.1.14 on 2022-07-26 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0022_informationdesk_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationdesk',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
