# Generated by Django 3.2.15 on 2022-09-27 08:14

from django.db import migrations
import datetime


def update_begin_date(apps, schema_editor):
    TouristicEvent = apps.get_model('tourism', 'TouristicEvent')
    TouristicEvent.objects.filter(
        begin_date__isnull=True
    ).update(
        begin_date=datetime.date(1970, 1, 1)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0027_touristicevent_bookable'),
    ]

    operations = [
        migrations.RunPython(update_begin_date, reverse_code=migrations.RunPython.noop)
    ]
