
# Generated by Django 3.2.15 on 2022-09-28 15:17
from django.db.models import F , Value
from django.db.models.functions import Concat
from django.db import migrations


def clean_participants_number(apps, schema_editor):
    TouristicEvent = apps.get_model('tourism', 'TouristicEvent')

    TouristicEvent.objects.exclude(
        participant_number__iregex=r'^[0-9]+$'
    ).exclude(
        participant_number__exact=''
    ).update(
        practical_info=Concat(F('practical_info'), Value('| Participant :'), F('participant_number')),
        participant_number=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0029_auto_20220927_0901'),
    ]

    operations = [
        migrations.RunPython(clean_participants_number, reverse_code=migrations.RunPython.noop)
    ]
