
# Generated by Django 3.2.15 on 2022-09-28 15:17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0030_auto_20220928_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicevent',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacity')
        )
    ]
