# Generated by Django 3.2.15 on 2022-09-27 15:01


import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0031_auto_20220927_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristicEventPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.PointField(spatial_index=False, srid=settings.SRID)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='touristiceventplace',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='place_geom_gist_idx'),
        ),
        migrations.AddField(
            model_name='touristicevent',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='touristicevents', to='tourism.touristiceventplace', verbose_name='Place'),
        ),
    ]
