# Generated by Django 3.2.15 on 2022-10-03 09:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0034_touristicevent_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristicEventPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2154)),
            ],
            options={
                'verbose_name': 'Event place',
                'verbose_name_plural': 'Event places',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='touristicevent',
            name='start_time',
            field=models.TimeField(blank=True, help_text='11:00, 23:30', null=True, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='touristicevent',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Select a place to auto-locate event on map', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='touristicevents', to='tourism.touristiceventplace', verbose_name='Event place'),
        ),
    ]
