# Generated by Django 3.2.15 on 2022-10-03 09:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0034_touristicevent_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="TouristicEventPlace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(srid=settings.SRID),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event place",
                "verbose_name_plural": "Event places",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="touristicevent",
            name="place",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a place in the list or locate the event directly on the map",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="touristicevents",
                to="tourism.touristiceventplace",
                verbose_name="Event place",
            ),
        ),
    ]
