# Generated by Django 3.2.15 on 2022-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0035_auto_20221003_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicevent',
            name='intervention_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Intervention duration'),
        ),
        migrations.AddField(
            model_name='touristicevent',
            name='preparation_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preparation duration'),
        ),
    ]
