# Generated by Django 3.2.15 on 2022-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0029_auto_20220922_1107'),
        ('tourism', '0036_remove_touristicevent_participant_number'),
    ]

    operations = [
    ]
