# Generated by Django 3.2.15 on 2022-11-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0037_merge_20221018_1050'),
        ('tourism', '0038_auto_20221107_0939'),
    ]

    operations = [
    ]
