# Generated by Django 3.2.18 on 2023-04-07 09:47

from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0011_alter_userprofile_structure'),
        ('common', '0031_auto_20230407_0947'),
        ('tourism', '0039_auto_20221110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristiccontent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='tourism.touristiccontentcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='touristiccontent',
            name='label_accessibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='tourism.labelaccessibility', verbose_name='Label accessibility'),
        ),
        migrations.AlterField(
            model_name='touristiccontent',
            name='reservation_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.reservationsystem', verbose_name='Reservation system'),
        ),
        migrations.AlterField(
            model_name='touristiccontent',
            name='structure',
            field=models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.PROTECT, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='touristicevent',
            name='structure',
            field=models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.PROTECT, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='touristicevent',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tourism.touristiceventtype', verbose_name='Type'),
        ),
    ]
