# Generated by Django 3.2.18 on 2023-05-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0041_alter_touristiceventparticipantcount_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationdesk',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desks', to='tourism.informationdesktype', verbose_name='Type'),
        ),
    ]
