# Generated by Django 3.2.19 on 2023-08-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0042_alter_informationdesk_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TouristicEventOrganizer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=256, verbose_name="Label")),
            ],
            options={
                "verbose_name": "Organizer",
                "verbose_name_plural": "Organizers",
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="touristicevent",
            name="organizer_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="touristicevent",
                to="tourism.touristiceventorganizer",
                verbose_name="Organizer",
            ),
        ),
    ]
