# Generated by Django 3.2.19 on 2023-08-04 13:17

from django.db import migrations


def create_organizer_fk(apps, schema_editor):
    TouristicEventModel = apps.get_model('tourism', 'TouristicEvent')
    OrganizerModel = apps.get_model('tourism', 'Organizer')
    organizers = []
    for row in TouristicEventModel.objects.all():
        organizers.append(OrganizerModel(label=row.label))
    OrganizerModel.objects.bulk_create(organizers)


def reverse_create_organizer_fk(apps, schema_editor):
    OrganizerModel = apps.get_model('tourism', 'Organizer')
    for row in OrganizerModel.objects.all():
        for event in row.touristicevents.all():
            event.organizer = row.label
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0043_auto_20230804_1317'),
    ]

    operations = [
        migrations.RunPython(create_organizer_fk, reverse_create_organizer_fk),
    ]
