# Generated by Django 3.2.19 on 2023-08-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0044_deplace_organizer_to_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristicevent',
            name='organizer',
        ),
    ]
