# Generated by Django 3.2.20 on 2023-08-24 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0046_rename_organizer_temp_touristicevent_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristiceventorganizer',
            name='date_insert',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Insertion date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristiceventorganizer',
            name='date_update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='touristiceventorganizer',
            name='date_insert',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Insertion date'),
        ),
    ]
