# Generated by Django 3.2.23 on 2023-12-20 09:52

from django.db import migrations, models


def forward_func(apps, schema_editors):
    ToursticEvent = apps.get_model("tourism", "TouristicEvent")
    for event in ToursticEvent.objects.all():
        if event.organizer:
            event.organizers.add(event.organizer)


def reverse_func(apps, schema_editors):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0049_alter_touristiccontentcategory_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristicevent",
            name="organizers",
            field=models.ManyToManyField(
                blank=True,
                related_name="touristicevent",
                to="tourism.TouristicEventOrganizer",
                verbose_name="Organizers",
            ),
        ),
        migrations.RunPython(forward_func, reverse_func),
        migrations.RemoveField(
            model_name="touristicevent",
            name="organizer",
        ),
    ]
