# Generated by Django 3.2.23 on 2023-12-13 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0049_alter_touristiccontentcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicevent',
            name='price',
            field=models.FloatField(blank=True, help_text='0 mean free', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
