# Generated by Django 3.2.23 on 2024-02-26 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0049_alter_touristiccontentcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0 mean free', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
