# Generated by Django 3.2.24 on 2024-02-29 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0050_alter_touristiceventorganizer_label"),
        ("tourism", "0050_auto_20231220_0952"),
    ]

    operations = []
