# Generated by Django 3.2.24 on 2024-02-29 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0050_touristicevent_price"),
        ("tourism", "0051_merge_20240229_1225"),
    ]

    operations = []
