# Generated by Django 3.2.25 on 2024-04-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0053_alter_touristicevent_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristiccontent',
            options={'ordering': ('name',), 'verbose_name': 'Touristic content', 'verbose_name_plural': 'Touristic contents'},
        ),
    ]
