# Generated by Django 3.2.23 on 2024-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0053_alter_touristicevent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristiceventorganizer',
            name='label',
            field=models.CharField(max_length=256, verbose_name='OrganizerLabel'),
        ),
    ]
