# Generated by Django 4.2.19 on 2025-03-12 16:50

from django.db import migrations
import magic


def mimetype(photo):
    if not photo:
        return None
    with photo.open('rb') as file:
        file.seek(0)
        mt = magic.from_buffer(file.read(), mime=True)
        return mt


def is_an_image(mimetype):
    return False if not mimetype else mimetype.split('/')[0].startswith('image')


def delete_non_image_photos(apps, schema_editor):
    InformationDesk = apps.get_model("tourism", "InformationDesk")
    for info_desk in InformationDesk.objects.all():
        if not is_an_image(mimetype(info_desk.photo)):
            info_desk.photo = None
            info_desk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0054_alter_touristiccontent_options'),
    ]

    operations = [
        migrations.RunPython(delete_non_image_photos, migrations.RunPython.noop)
    ]
