# Generated by Django 4.2.19 on 2025-03-12 16:51

import paperclip.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0055_auto_20250312_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationdesk",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="upload",
                validators=[paperclip.validators.FileMimetypeValidator()],
                verbose_name="Photo",
            ),
        ),
    ]
