# Generated by Django 4.2.22 on 2025-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0057_auto_20250611_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationdesk",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="touristiccontent",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="touristicevent",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
    ]
