# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models


def deplace_data(apps, schema_editor):
    # We can't import Infrastructure models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Old_Signage = apps.get_model('infrastructure', 'Signage')
    New_Signage = apps.get_model('signage', 'Signage')
    for signage in Old_Signage.objects.all().values():
        signage['old_type'] = signage['type']
        del signage['type']
        New_Signage.objects.create(**signage)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0010_replace_table_name'),
        ('common', '0003_auto_20180608_1236'),
        ('core', '0008_aggregation_infrastructure'),
        ('authent', '0003_auto_20181203_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signage',
            fields=[
                ('published', models.BooleanField(db_column=b'public', default=False, help_text='Online', verbose_name='Published')),
                ('publication_date', models.DateField(blank=True, db_column=b'date_publication', editable=False, null=True, verbose_name='Publication date')),
                ('topo_object', models.OneToOneField(db_column=b'evenement', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Topology')),
                ('name', models.CharField(db_column=b'nom', help_text='Reference, code, ...', max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_column=b'description', help_text='Specificites', verbose_name='Description')),
                ('implantation_year', models.PositiveSmallIntegerField(db_column=b'annee_implantation', null=True, verbose_name='Implantation year')),
                ('eid', models.CharField(blank=True, db_column=b'id_externe', max_length=1024, null=True, verbose_name='External id')),
                ('code', models.CharField(blank=True, db_column=b'code_commune', max_length=250, null=True, verbose_name='Code commune')),
                ('printed_elevation', models.IntegerField(blank=True, db_column=b'altitude_imprimee', null=True, verbose_name='Printed Elevation')),
                ('administrator', models.ForeignKey(db_column=b'gestionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Organism', verbose_name='Administrator')),
                ('condition', models.ForeignKey(blank=True, db_column=b'etat', null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.InfrastructureCondition', verbose_name='Condition')),
                ('old_type', models.ForeignKey(db_column=b'old_type', on_delete=django.db.models.deletion.CASCADE, to='infrastructure.InfrastructureType', verbose_name='Old Type')),
            ],
            options={
                'verbose_name': 'Signage',
                'verbose_name_plural': 'Signages',
            },
            bases=('core.topology', models.Model),
        ),
        migrations.CreateModel(
            name='SignageSealing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_column=b'etat', max_length=250, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, db_column=b'structure', default=geotrek.authent.models.default_structure_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.Structure', verbose_name='Related structure')),
            ],
            options={
                'db_table': 'a_b_scellement',
                'verbose_name': 'Signage Sealing',
                'verbose_name_plural': 'Signages Sealing',
            },
        ),
        migrations.CreateModel(
            name='SignageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictogram', models.FileField(blank=True, db_column=b'picto', max_length=512, null=True, upload_to=b'upload', verbose_name='Pictogram')),
                ('label', models.CharField(db_column=b'nom', max_length=128)),
                ('structure', models.ForeignKey(blank=True, db_column=b'structure', default=geotrek.authent.models.default_structure_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.Structure', verbose_name='Related structure')),
            ],
            options={
                'db_table': 'a_b_signaletique',
                'verbose_name': 'Signage Type',
                'verbose_name_plural': 'Signage Types',
            },
        ),
        migrations.AddField(
            model_name='signage',
            name='sealing',
            field=models.ForeignKey(db_column=b'scellement', null=True, on_delete=django.db.models.deletion.CASCADE, to='signage.SignageSealing', verbose_name='Sealing'),
        ),
        migrations.AddField(
            model_name='signage',
            name='structure',
            field=models.ForeignKey(db_column=b'structure', default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.CASCADE, to='authent.Structure', verbose_name='Related structure'),
        ),
        migrations.AddField(
            model_name='signage',
            name='type',
            field=models.ForeignKey(db_column=b'type', on_delete=django.db.models.deletion.CASCADE, to='signage.SignageType', verbose_name='Type'),
        ),
        migrations.RunPython(deplace_data),
    ]
