# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aggregation_infrastructure'),
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blade',
            name='deleted',
            field=models.BooleanField(db_column=b'supprime', default=False, editable=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='blade',
            name='topology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blades_set', to='core.Topology', verbose_name='Blades'),
        ),
    ]
