# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_deplace_signage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signage',
            name='old_type',
        ),
    ]
