# Generated by Django 1.11.14 on 2019-01-14 13:29

from django.db import migrations


def attachment_signage(apps, schema_editor):
    AttachmentModel = apps.get_model("common", "Attachment")
    SignageModel = apps.get_model("signage", "Signage")
    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    signage = ContentTypeModel.objects.get(app_label="signage", model="signage")
    attachments = AttachmentModel.objects.filter(
        content_type__model="baseinfrastructure",
        object_id__in=SignageModel.objects.all().values_list("pk", flat=True),
    )
    attachments.update(content_type=signage)


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0003_verbose_blade_signage"),
    ]

    operations = [
        migrations.RunPython(attachment_signage),
    ]
