# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_remove_old_signage'),
        ('signage', '0003_remove_signage_old_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signage',
            table='a_t_signaletique',
        ),
    ]
