# Generated by Django 2.2.12 on 2020-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0013_auto_20200423_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signage",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Code"
            ),
        ),
    ]
