# Generated by Django 2.0.13 on 2020-04-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0014_auto_20200428_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="pictogram_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Pictogram"
            ),
        ),
    ]
