# Generated by Django 2.2.12 on 2020-05-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0015_auto_20200429_1208"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blade",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="blade",
            name="structure",
        ),
        migrations.RemoveField(
            model_name="line",
            name="structure",
        ),
        migrations.AlterField(
            model_name="line",
            name="blade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="signage.Blade",
                verbose_name="Blade",
            ),
        ),
    ]
