# Generated by Django 3.1.13 on 2021-09-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0020_auto_20210121_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signage",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signages",
                to="signage.signagetype",
                verbose_name="Type",
            ),
        ),
    ]
