# Generated by Django 3.1.14 on 2022-03-14 14:41

from django.conf import settings
from django.db import migrations


def forward(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for lang in settings.MODELTRANSLATION_LANGUAGES:
            cursor.execute(
                f"UPDATE signage_signage SET published_{lang.replace('-', '_')} = True WHERE published = True;  "
            )


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0022_auto_20220314_1048"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
