# Generated by Django 3.1.14 on 2022-10-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0024_signage_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='signage.direction', verbose_name='Direction'),
        ),
    ]
