# Generated by Django 3.1.14 on 2022-10-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0025_blade_direction_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="signage.direction",
                verbose_name="Direction",
            ),
        ),
    ]
