# Generated by Django 3.2.15 on 2022-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0025_auto_20220921_1616'),
        ('signage', '0026_line_direction'),
    ]

    operations = [
    ]
