# Generated by Django 3.2.18 on 2023-04-07 09:47

from django.db import migrations, models
import django.db.models.deletion
import geotrek.authent.models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0011_alter_userprofile_structure'),
        ('infrastructure', '0033_auto_20230407_0943'),
        ('common', '0031_auto_20230407_0947'),
        ('signage', '0027_auto_20221110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signage.bladetype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='bladetype',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='sealing',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='signage',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.infrastructurecondition', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='signage',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.organism', verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='signage',
            name='sealing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='signage.sealing', verbose_name='Sealing'),
        ),
        migrations.AlterField(
            model_name='signage',
            name='structure',
            field=models.ForeignKey(default=geotrek.authent.models.default_structure_pk, on_delete=django.db.models.deletion.PROTECT, to='authent.structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='signage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signages', to='signage.signagetype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='signagetype',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authent.structure', verbose_name='Related structure'),
        ),
    ]
