# Generated by Django 3.2.19 on 2023-06-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0035_auto_20230613_0917'),
        ('signage', '0030_auto_20230509_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='signage',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.infrastructureaccessmean', verbose_name='Access mean'),
        ),
    ]
