# Generated by Django 3.2.19 on 2023-07-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0031_signage_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Text'),
        ),
    ]
