# Generated by Django 3.2.16 on 2023-01-26 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0034_migrate_pictogram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="pictogram_name",
        ),
    ]
