# Generated by Django 3.2.21 on 2023-10-23 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0037_auto_20231016_1331"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signagecondition",
            options={
                "ordering": ["label"],
                "verbose_name": "Signage Condition",
                "verbose_name_plural": "Signage Conditions",
            },
        ),
        migrations.RemoveField(
            model_name="blade",
            name="condition",
        ),
    ]
