# Generated by Django 3.2.21 on 2023-12-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0039_signage_access_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signage',
            name='access',
        ),
    ]
