# Generated by Django 5.2.11 on 2026-03-12 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0044_auto_20250611_1417"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blade",
            name="topology",
        ),
    ]
