# Generated by Django 4.2.23 on 2025-08-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0044_auto_20250611_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blade',
            name='topology',
        ),
    ]
