# Generated by Django 4.2.22 on 2025-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0044_auto_20250611_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signage',
            name='eid',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='External id'),
        ),
    ]
