# Generated by Django 5.2.12 on 2026-03-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0045_remove_blade_topology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blade",
            name="signage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blades",
                to="signage.signage",
                verbose_name="Signage",
            ),
        ),
    ]
