# Generated by Django 5.2.14 on 2026-06-09 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0046_alter_blade_signage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="line",
            unique_together=set(),
        ),
    ]
