# Generated by Django 5.2.15 on 2026-07-02 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0047_alter_line_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blade",
            name="deleted",
        ),
    ]
