# Generated by Django 5.2.15 on 2026-07-02 09:46

from django.db import migrations


def remove_deleted_blades(apps, schema_editor):
    blade_model = apps.get_model("signage", "Blade")
    qs = blade_model.objects.filter(deleted=True)
    qs.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0047_alter_line_unique_together"),
    ]

    operations = [
        migrations.RunPython(remove_deleted_blades, migrations.RunPython.noop),
    ]
