# Generated by Django 5.2.16 on 2026-07-31 08:19

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0047_alter_line_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blade",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="blade",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="bladecondition",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="bladecondition",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="bladetype",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="bladetype",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="linepictogram",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="linepictogram",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="sealing",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="sealing",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="signagecondition",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="signagecondition",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="signagetype",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="signagetype",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
    ]
