# Generated by Django 5.2.15 on 2026-07-02 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signage", "0048_remove_blade_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blade",
            name="deleted",
        ),
    ]
