# Generated by Django 3.1.5 on 2021-01-12 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("altimetry", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS mnt (rid serial primary key, rast raster);"
        ),
        migrations.RunSQL("INSERT INTO altimetry_dem (rast) SELECT rast FROM mnt;"),
        migrations.RunSQL("DROP TABLE mnt;"),
    ]
