# Generated by Django 3.1.5 on 2021-01-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altimetry', '0002_import_mnt_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dem',
            old_name='rid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='dem',
            name='id',
            field=models.AutoField(db_column='rid', primary_key=True, serialize=False),
        ),
    ]
