upstream api {
    server api:8000;
}

upstream web {
    server web:8000;
}

map $http_origin $allow_origin {
    "~${RANDO_SERVER_NAME_PIPE}" $http_origin;
    default "";
}


server {
    listen 80;
    server_name _;
    server_tokens off;

    client_max_body_size 200M;
    proxy_read_timeout 600s;

    location ~ ^/api {
        proxy_set_header   X-Forwarded-Host     $host;
        proxy_set_header   X-Forwarded-Server   $host;
        proxy_set_header   X-Forwarded-Proto    $http_x_forwarded_proto;
        proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header   X-Real-IP            $remote_addr;
        proxy_set_header   Host                 $http_host;
        proxy_redirect     off;
        keepalive_timeout 0;
        proxy_pass         http://api;
        add_header Access-Control-Allow-Origin $allow_origin;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }

    location /media {
        alias /opt/geotrek-admin/var/media/;
        add_header Access-Control-Allow-Origin $allow_origin;
    }
    
    location /media_secure {
        internal;
        alias /opt/geotrek-admin/var/media;
    }

    location /static {
        alias /opt/geotrek-admin/var/static/;
    }

    location ~ ^/m/(?<remaining_path>.*)$ {
        root /;
        try_files /opt/geotrek-admin/var/frontend/dist/$remaining_path /opt/geotrek-admin/var/frontend/dist/index.html =404;
    }

    location ^~ /m/sw.js {
        alias /opt/geotrek-admin/var/frontend/dist/sw.js;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
        access_log off;
    }

    location = /m {
        return 307 /m/;
    }

    location ~ ^/mobile/(.*)$ {
        add_header Vary "Accept-Language";
	    add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        root /opt/geotrek-admin/var/mobile/;
        try_files /$http_accept_language/$1 /nolang/$1 =404;
        gzip on;
        gzip_types text/text text/plain text/xml text/css application/x-javascript application/javascript application/json;
        include mime.types;
        types {
            application/json geojson;
            application/gpx+xml gpx;
            application/x-font-ttf ttf;
        }
    }

    # Check if a file exists at /var/www/admin/ for the incoming request.
    try_files $uri @django;

    location @django {
        proxy_set_header   X-Forwarded-Host     $host;
        proxy_set_header   X-Forwarded-Server   $host;
        proxy_set_header   X-Forwarded-Proto    $http_x_forwarded_proto;
        proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header   X-Real-IP            $remote_addr;
        proxy_set_header   Host                 $http_host;
        proxy_redirect     off;
        keepalive_timeout 0;
        proxy_pass         http://web;
    }
}
