# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-02-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_auto_20200211_1036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsource",
            name="pictogram",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="upload",
                verbose_name="Pictogram",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="pictogram",
            field=models.FileField(
                max_length=512, null=True, upload_to="upload", verbose_name="Pictogram"
            ),
        ),
    ]
