# Generated by Django 2.2.14 on 2020-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_attachment_add_is_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ReservationSystem",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(
                                max_length=256, unique=True, verbose_name="Name"
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Reservation system",
                        "verbose_name_plural": "Reservation systems",
                        "ordering": ("name",),
                    },
                ),
            ],
            # Table already exists. See tourism/migrations/0012
            database_operations=[],
        ),
    ]
