# Generated by Django 3.1.4 on 2020-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="label",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
    ]
