# Generated by Django 3.1.13 on 2021-10-25 14:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_auto_20210528_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
