# Generated by Django 3.1.13 on 2021-09-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_auto_20210528_1232"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=128, unique=True, verbose_name="Licence Name")),
            ],
            options={
                "verbose_name": "Attachment licence",
                "verbose_name_plural": "Attachment licences",
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="license",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.licence", verbose_name="License"),
        ),
    ]
