# Generated by Django 3.1.13 on 2021-10-25 14:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_auto_20211025_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
