# Generated by Django 3.1.13 on 2021-10-26 09:30

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20211025_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='uuid',
            field=models.UUIDField(default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True),
        ),
    ]
