# Generated by Django 3.1.14 on 2022-04-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0006_auto_20220127_0944"),
        ("common", "0024_auto_20220408_0933"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="License name"
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment license",
                "verbose_name_plural": "Attachment licenses",
                "ordering": ["label"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="accessibilityattachment",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.license",
                verbose_name="License",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.license",
                verbose_name="License",
            ),
        ),
    ]
