# Generated by Django 3.1.14 on 2022-04-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperclip', '__first__'),
        ('common', '0024_auto_20220408_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paperclip.license')),
                ('pictogram', models.FileField(blank=True, max_length=512, null=True, upload_to='upload', verbose_name='Pictogram')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['label'],
            },
            bases=('paperclip.license', models.Model),
        ),
        migrations.AddField(
            model_name='attachment',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.license', verbose_name='License'),
        ),
    ]
