# Generated by Django 3.2.15 on 2022-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0027_flush_cache_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsource",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Name"),
        ),
    ]
