# Generated by Django 3.2.16 on 2023-01-19 09:32

from django.db import migrations, models
import geotrek.common.models
import paperclip.models
import paperclip.validators


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_alter_recordsource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilityattachment',
            name='attachment_accessibility_file',
            field=models.ImageField(blank=True, max_length=512, upload_to=geotrek.common.models.attachment_accessibility_upload, validators=[paperclip.validators.FileMimetypeValidator()], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=512, upload_to=paperclip.models.attachment_upload, validators=[paperclip.validators.FileMimetypeValidator()], verbose_name='File'),
        ),
    ]
