# Generated by Django 3.2.15 on 2022-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_hdviewpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdviewpoint',
            name='picture',
            field=models.FileField(upload_to='hdviewpoints/', verbose_name='Picture'),
        ),
    ]
