# Generated by Django 3.2.16 on 2023-02-02 15:35

import paperclip.models
import paperclip.validators
from django.db import migrations, models

import geotrek.common.models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_hdviewpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilityattachment",
            name="random_suffix",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="attachment",
            name="random_suffix",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="accessibilityattachment",
            name="attachment_accessibility_file",
            field=models.ImageField(
                blank=True,
                max_length=512,
                upload_to=geotrek.common.models.attachment_accessibility_upload,
                validators=[paperclip.validators.FileMimetypeValidator()],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment_file",
            field=models.FileField(
                blank=True,
                max_length=512,
                upload_to=paperclip.models.attachment_upload,
                validators=[paperclip.validators.FileMimetypeValidator()],
                verbose_name="File",
            ),
        ),
    ]
