# Generated by Django 3.2.16 on 2023-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20230123_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityattachment',
            name='random_suffix',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
