# Generated by Django 3.2.18 on 2023-04-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cirkwi", "0003_auto_20200406_1353"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authent", "0011_alter_userprofile_structure"),
        ("common", "0030_auto_20230202_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityattachment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilityattachment",
            name="creator",
            field=models.ForeignKey(
                help_text="User that uploaded",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_attachments_accessibility",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilityattachment",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.license",
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="filetype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="hdviewpoint",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="hdviewpoint",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.license",
                verbose_name="License",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="organism",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="cirkwi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cirkwi.cirkwitag",
                verbose_name="Cirkwi tag",
            ),
        ),
    ]
