# Generated by Django 3.2.15 on 2022-11-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_alter_hdviewpoint_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hdviewpoint',
            options={'permissions': (('read_hdviewpoint', 'Can read hd view point'),), 'verbose_name': 'HD View', 'verbose_name_plural': 'HD Views'},
        ),
    ]
