# Generated by Django 3.2.18 on 2023-05-04 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0033_auto_20230503_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilityattachment',
            name='creator',
            field=models.ForeignKey(help_text='User that uploaded', on_delete=django.db.models.deletion.PROTECT, related_name='created_attachments_accessibility', to='auth.user', verbose_name='Creator'),
        ),
    ]
