# Generated by Django 3.2.19 on 2023-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_label_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='published',
            field=models.BooleanField(blank=True, default=True, help_text='Visible on Geotrek-rando', verbose_name='Published'),
        ),
    ]
