# Generated by Django 3.2.19 on 2023-07-19 14:50

from django.db import migrations


def set_labels_published(apps, schema):
    Label = apps.get_model('common', 'Label')
    Label.objects.update(published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_label_published'),
    ]

    operations = [
        migrations.RunPython(set_labels_published),
    ]
