# Generated by Django 4.2.23 on 2025-07-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_alter_recordsource_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetportal',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='targetportal',
            name='facebook_image_height',
        ),
        migrations.RemoveField(
            model_name='targetportal',
            name='facebook_image_url',
        ),
        migrations.RemoveField(
            model_name='targetportal',
            name='facebook_image_width',
        ),
    ]
