# Generated by Django 4.2.23 on 2025-07-10 09:43

from django.db import migrations, models

import geotrek.common.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="link_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTML template for external source links",
                validators=[geotrek.common.utils.validators.validate_html_template],
                verbose_name="Link template",
            ),
        ),
    ]
