# Generated by Django 5.2.7 on 2025-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_alter_provider_link_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetportal",
            name="description",
            field=models.TextField(
                default="",
                help_text="Description on Geotrek-rando",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="targetportal",
            name="title",
            field=models.CharField(
                default="",
                help_text="Title on Geotrek-rando",
                max_length=50,
                verbose_name="Title Rando",
            ),
        ),
    ]
