# Generated by Django 1.11.14 on 2019-10-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_auto_20190925_1243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comfort",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="pathsource",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="stake",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
    ]
