# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_auto_20191029_1110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trail",
            name="arrival",
            field=models.CharField(
                blank=True, db_column="arrivee", max_length=64, verbose_name="Arrival"
            ),
        ),
        migrations.AlterField(
            model_name="trail",
            name="departure",
            field=models.CharField(
                blank=True, db_column="depart", max_length=64, verbose_name="Departure"
            ),
        ),
    ]
