# Generated by Django 3.1.5 on 2021-01-26 09:56
import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_clean_spatial_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                srid=settings.SRID
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="geom_cadastre",
            field=django.contrib.gis.db.models.fields.LineStringField(
                editable=False, null=True, srid=settings.SRID
            ),
        ),
        migrations.AlterField(
            model_name="topology",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                default=None,
                editable=(not settings.TREKKING_TOPOLOGY_ENABLED),
                null=True,
                srid=settings.SRID,
            ),
        ),
        migrations.RunSQL(
            "CREATE INDEX core_path_start_point_idx ON core_path USING gist(ST_StartPoint(geom));"
        ),
        migrations.RunSQL(
            "CREATE INDEX core_path_end_point_idx ON core_path USING gist(ST_EndPoint(geom));"
        ),
    ]
