# Generated by Django 3.1.5 on 2021-01-26 09:56
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_clean_spatial_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=settings.SRID),
        ),
        migrations.AlterField(
            model_name='path',
            name='geom_cadastre',
            field=django.contrib.gis.db.models.fields.LineStringField(editable=False, null=True, srid=settings.SRID),
        ),
        migrations.AlterField(
            model_name='topology',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, editable=False, null=True, srid=settings.SRID),
        ),
    ]
