# Generated by Django 3.1.5 on 2021-02-10 12:52

from django.conf import settings
from django.db import migrations


def clean_tmp_topologies(apps, schema_editor):
    Topology = apps.get_model('core', 'topology')
    Topology.objects.filter(kind__in=('TMP', 'TOPOLOGY')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210126_0956'),
    ] + [
        ('maintenance', '0017_auto_20210211_0825'),
    ] if 'geotrek.maintenance' in settings.INSTALLED_APPS else []

    operations = [
        migrations.RunPython(clean_tmp_topologies),
    ]
