# Generated by Django 3.1.5 on 2021-02-10 12:52

from django.conf import settings
from django.db import migrations


def clean_tmp_topologies(apps, schema_editor):
    Topology = apps.get_model('core', 'topology')

    # Fix kind of topologies directly linked to interventions
    if 'geotrek.maintenance' in settings.INSTALLED_APPS:
        ContentType = apps.get_model('contenttypes', 'contenttype')
        Intervention = apps.get_model('maintenance', 'intervention')
        topology_ct = ContentType.objects.get_for_model(Topology)
        topo_ids = Intervention.objects.filter(target_type=topology_ct).values_list('target_id', flat=True)
        topos = Topology.objects.filter(id__in=topo_ids).filter(kind__in=('TMP', 'TOPOLOGY'))
        n = topos.update(kind='INTERVENTION')
        if n:
            print("\n  WARNING! Updated {} topologies directly linked to interventions with a wrong kind".format(n))

    # Clean tmp topologies
    Topology.objects.filter(kind__in=('TMP', 'TOPOLOGY')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210126_0956'),
    ]

    operations = [
        migrations.RunPython(clean_tmp_topologies),
    ]
