# Generated by Django 3.1.13 on 2021-10-22 11:04

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("core", "Path")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_path_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
