# Generated by Django 3.1.13 on 2021-10-22 11:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_auto_20211022_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
