# Generated by Django 3.1.13 on 2021-10-22 12:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_auto_20211022_1104"),
    ]

    operations = [
        migrations.AddField(
            model_name="topology",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
