# Generated by Django 3.1.13 on 2021-10-22 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211022_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
