# Generated by Django 3.1.14 on 2022-07-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0009_userprofile_extended_username"),
        ("core", "0031_certificationlabel_certificationstatus_certificationtrail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificationstatus",
            options={
                "ordering": ["label"],
                "verbose_name": "Certification status",
                "verbose_name_plural": "Certification statuses",
            },
        ),
        migrations.AlterField(
            model_name="certificationtrail",
            name="certification_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certifications",
                to="core.certificationlabel",
                verbose_name="Certification label",
            ),
        ),
        migrations.AlterField(
            model_name="certificationtrail",
            name="certification_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certifications",
                to="core.certificationstatus",
                verbose_name="Certification status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificationlabel",
            unique_together={("label", "structure")},
        ),
        migrations.AlterUniqueTogether(
            name="certificationstatus",
            unique_together={("label", "structure")},
        ),
    ]
