# Generated by Django 3.2.15 on 2022-09-19 12:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220909_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, null=True, spatial_index=False, srid=2154),
        ),
    ]
