# Generated by Django 4.2.18 on 2025-01-30 09:12

from django.db import migrations


# This migration used to pre-generate the pgRouting topology graph.
# It is now a no-op, as it was redundant and relied on functions that
# have been removed in pgRouting 4.0.
class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_path_source_pgr_path_target_pgr"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
