# Generated by Django 4.2.18 on 2025-01-30 09:12

from django.db import migrations

from django.core.management import call_command


def generate_pgr_network_topology(apps, schema_editor):
    call_command('generate_pgr_network_topology')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_path_source_pgr_path_target_pgr'),
    ]

    operations = [
        migrations.RunPython(generate_pgr_network_topology, migrations.RunPython.noop),
    ]
