# Generated by Django 4.2.20 on 2025-04-02 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_auto_20250130_0912"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE core_path DROP CONSTRAINT IF EXISTS l_t_troncon_geom_isvalid;
            ALTER TABLE core_path DROP CONSTRAINT IF EXISTS core_path_geom_isvalid;
            ALTER TABLE core_path DROP CONSTRAINT IF EXISTS troncons_geom_issimple;
            ALTER TABLE core_path DROP CONSTRAINT IF EXISTS l_t_troncon_geom_issimple;
            ALTER TABLE core_path DROP CONSTRAINT IF EXISTS core_path_geom_issimple;
            """
        )
    ]
