# Generated by Django 4.2.21 on 2025-06-10 08:44

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_provider'),
        ('core', '0040_path_core_path_geom_is_valid_and_more'),
    ]

    operations = [
        # add a new fk field for provider
        migrations.AddField(
            model_name='path',
            name='provider_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='trail',
            name='provider_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.provider', verbose_name='Provider'),
        )
    ]