# Generated by Django 4.2.21 on 2025-06-10 14:04

from django.db import migrations

def forward_fill_provider(apps, schema_editor):
    provider_model = apps.get_model('common', 'Provider')

    models = ["Trail", "Path"]
    for model_name in models:
        model = apps.get_model('core', model_name)

        for obj in model.objects.all():
            if obj.provider:
                provider, _ = provider_model.objects.get_or_create(name=obj.provider)
                obj.provider_fk = provider
                obj.save()

def backward_fill_provider(apps, schema_editor):
    models = ["Trail", "Path"]
    for model_name in models:
        model = apps.get_model('core', model_name)

        for obj in model.objects.all():
            if obj.provider:
                obj.provider = obj.provider_fk.name
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_path_provider_fk_trail_provider_fk'),
    ]

    operations = [
        # Populate provider_fk field with provider values
        migrations.RunPython(forward_fill_provider, backward_fill_provider),
    ]
