# Generated by Django 4.2.22 on 2025-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_path_provider_fk_trail_provider_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="trail",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
    ]
