# Generated by Django 4.2.21 on 2025-06-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20250610_1604'),
    ]

    operations = [
        # Delete provider field
        migrations.RemoveField(
            model_name='trail',
            name='provider'
        ),
        migrations.RemoveField(
            model_name='path',
            name='provider'
        ),


        # Rename provider_fk field
        migrations.RenameField(
            model_name='path',
            old_name='provider_fk',
            new_name='provider'
        ),
        migrations.RenameField(
            model_name='trail',
            old_name='provider_fk',
            new_name='provider'
        )
    ]


