# Generated by Django 5.2.7 on 2025-10-09 08:56

from django.core.management import call_command
from django.db import migrations


def regenerate_pgr_network_topology(apps, schema_editor):
    Path = apps.get_model("core", "Path")
    Path.objects.all().update(source_pgr=None, target_pgr=None)
    call_command("generate_pgr_network_topology")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_path_eid_alter_trail_eid"),
    ]

    operations = [
        migrations.RunPython(
            regenerate_pgr_network_topology, migrations.RunPython.noop
        ),
    ]
