# Generated by Django 5.2.7 on 2025-10-09 08:56

from django.db import migrations


# This migration used to pre-generate the pgRouting topology graph.
# It is now a no-op, as it was redundant and relied on functions that
# have been removed in pgRouting 4.0.
class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_path_eid_alter_trail_eid"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
