# Generated by Django 5.2.7 on 2025-10-09 08:56

from django.conf import settings
from django.db import connection, migrations


def regenerate_pgr_network_topology(apps, schema_editor):
    cursor = connection.cursor()
    flush_query = """UPDATE core_path SET source = NULL, target = NULL"""
    cursor.execute(flush_query)
    generation_query = """
            SELECT
                pgr_createTopology(
                    'core_path',
                    %s::float,
                    'geom',
                    'id'
                )
            """
    cursor.execute(generation_query, [settings.PGROUTING_TOLERANCE])
    return ("OK",) == cursor.fetchone()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_path_eid_alter_trail_eid"),
    ]

    operations = [
        migrations.RunPython(
            regenerate_pgr_network_topology, migrations.RunPython.noop
        ),
    ]
