# Generated by Django 5.2.7 on 2025-10-15 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_auto_20251009_0856"),
        ("core", "0043_path_length_2d"),
    ]

    operations = []
