# Generated by Django 5.2.7 on 2025-10-24 08:16

import django.contrib.gis.db.models.functions
from django.db import migrations, models

import geotrek.common.functions


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_merge_0043_auto_20251009_0856_0043_path_length_2d"),
    ]

    operations = [
        migrations.AddField(
            model_name="topology",
            name="length_2d",
            field=models.GeneratedField(
                db_persist=True,
                expression=geotrek.common.functions.LengthSpheroid(
                    django.contrib.gis.db.models.functions.Transform("geom", 4326),
                    models.Value('SPHEROID["GRS_1980",6378137,298.257222101]'),
                ),
                output_field=models.FloatField(),
                verbose_name="Length 2D",
            ),
        ),
    ]
