# Generated by Django 5.2.9 on 2025-12-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_topology_length_2d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topology",
            name="geom_need_update",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
