# Generated by Django 5.2.9 on 2026-01-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_topology_geom_need_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topology',
            name='length_2d',
        ),
    ]
