# Generated by Django 5.2.9 on 2026-01-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_topology_length_2d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='length_2d',
        ),
    ]
