# Generated by Django 5.2.10 on 2026-02-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_path_length_2d"),
    ]

    operations = [
        migrations.AddField(
            model_name="topology",
            name="decoupled",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
