# Generated by Django 5.2.15 on 2026-08-05 16:05

from django.db import migrations


# The next migration adds indexes on the source_pgr and target_pgr fields for the Path model.
# At this point, these indexes may have already been created by pgRouting functions
# that are removed in pgRouting 4.0.
# Before running the next migration, we need to remove these indexes if they already exist.
class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_path_length_2d"),
    ]

    operations = [
        migrations.RunSQL(
            ["DROP INDEX IF EXISTS core_path_source_idx;"], migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            ["DROP INDEX IF EXISTS core_path_target_idx;"], migrations.RunSQL.noop
        ),
    ]
