# Generated by Django 5.2.10 on 2026-02-02 16:23

from django.contrib.gis.db.models.functions import GeoFunc
from django.db import migrations
from django.db.models import CharField, Count, Q


class GeometryType(GeoFunc):
    """GeometryType postgis function"""

    output_field = CharField()
    function = "GeometryType"


def couple_topologies(apps, schema_editor):
    Topology = apps.get_model("core", "Topology")
    topologies = Topology.objects.all().annotate(
        geometry_type=GeometryType("geom"),
        nb_aggregations=Count("aggregations"),
    )

    # Coupled topologies' geometry types must be allowed
    geometry_types_allowed = {
        "TOPOLOGY": ["LINESTRING", "POINT"],
        "TRAIL": ["LINESTRING"],
        "INFRASTRUCTURE": ["LINESTRING", "POINT"],
        "PHYSICALEDGE": ["LINESTRING"],
        "LANDEDGE": ["LINESTRING"],
        "COMPETENCEEDGE": ["LINESTRING"],
        "WORKMANAGEMENTEDGE": ["LINESTRING"],
        "SIGNAGEMANAGEMENTEDGE": ["LINESTRING"],
        "CIRCULATIONEDGE": ["LINESTRING"],
        "INTERVENTION": ["LINESTRING", "POINT"],
        "SIGNAGE": ["POINT"],
        "TREK": ["LINESTRING"],
        "POI": ["POINT"],
    }
    has_allowed_geometry_type = Q()
    for kind, allowed in geometry_types_allowed.items():
        has_allowed_geometry_type |= Q(kind=kind, geometry_type__in=allowed)

    # Coupled topologies must have a valid geometry
    has_valid_geom = (
        Q(geom__isnull=False) & Q(geom__isvalid=True) & Q(geom__isempty=False)
    )

    # Coupled topologies must have at least one path aggregation
    has_path_aggregation = Q(nb_aggregations__gt=0)

    topologies_to_couple = topologies.filter(
        has_allowed_geometry_type & has_valid_geom & has_path_aggregation
    )
    topologies_to_couple.update(coupled=True)


class Migration(migrations.Migration):
    """Set all topologies with a valid geometry and path aggregations as "coupled"."""

    dependencies = [
        ("core", "0051_topology_coupled"),
    ]

    operations = [
        migrations.RunPython(couple_topologies, migrations.RunPython.noop),
    ]
