# Generated by Django 5.2.15 on 2026-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_remove_indexes_on_path_source_and_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="source_pgr",
            field=models.IntegerField(
                blank=True,
                db_column="source",
                db_index=True,
                editable=False,
                help_text="Internal field used by pgRouting",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="target_pgr",
            field=models.IntegerField(
                blank=True,
                db_column="target",
                db_index=True,
                editable=False,
                help_text="Internal field used by pgRouting",
                null=True,
            ),
        ),
    ]
