# Generated by Django 5.2.10 on 2026-02-02 16:23

from django.contrib.gis.db.models.functions import GeoFunc
from django.db import migrations
from django.db.models import CharField, Count, Q


class GeometryType(GeoFunc):
    """GeometryType postgis function"""

    output_field = CharField()
    function = "GeometryType"


def decouple_topologies(apps, schema_editor):
    Topology = apps.get_model("core", "Topology")
    topologies = Topology.objects.all().annotate(
        geometry_type=GeometryType("geom"),
        nb_aggregations=Count("aggregations"),
    )

    # Handle topologies with invalid geometries
    geometry_types_allowed = {
        "TOPOLOGY": ["LINESTRING", "POINT"],
        "TRAIL": ["LINESTRING"],
        "INFRASTRUCTURE": ["LINESTRING", "POINT"],
        "PHYSICALEDGE": ["LINESTRING"],
        "LANDEDGE": ["LINESTRING"],
        "COMPETENCEEDGE": ["LINESTRING"],
        "WORKMANAGEMENTEDGE": ["LINESTRING"],
        "SIGNAGEMANAGEMENTEDGE": ["LINESTRING"],
        "CIRCULATIONEDGE": ["LINESTRING"],
        "INTERVENTION": ["LINESTRING", "POINT"],
        "SIGNAGE": ["POINT"],
        "TREK": ["LINESTRING"],
        "POI": ["POINT"],
    }
    has_invalid_geom = (
        Q(geom__isnull=True) | Q(geom__isvalid=False) | Q(geom__isempty=True)
    )
    for kind, allowed in geometry_types_allowed.items():
        has_invalid_geom |= Q(kind=kind) & ~Q(geometry_type__in=allowed)

    # Handle topologies with no path aggregation
    has_no_path_aggregation = Q(nb_aggregations=0)

    topologies_to_decouple = topologies.filter(
        has_invalid_geom | has_no_path_aggregation
    )
    topologies_to_decouple.update(coupled=False)


class Migration(migrations.Migration):
    """Set all topologies with an invalid geometry/topology to "decoupled"."""

    dependencies = [
        ("core", "0051_topology_coupled"),
    ]

    operations = [
        migrations.RunPython(decouple_topologies, migrations.RunPython.noop),
    ]
