# Generated by Django 5.2.11 on 2026-03-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_set_topologies_as_decoupled"),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="is_being_split",
            field=models.BooleanField(
                default=False,
                db_default=False,
                editable=False,
                help_text="Internal field preventing geometry updates on related topologies during path splitting",
            ),
        ),
    ]
