# Generated by Django 5.2.15 on 2026-08-05 16:12

from django.db import migrations


# The next migration adds the PgRoutingNode model to store pgRouting topology nodes.
# At this point, a node table may have already been created by pgRouting functions
# that are removed in pgRouting 4.0.
# Before running the next migration, we need to drop this obsolete table if it exists.
class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_path_source_pgr_alter_path_target_pgr"),
    ]

    operations = [
        migrations.RunSQL(
            ["DROP TABLE IF EXISTS core_path_vertices_pgr;"], migrations.RunSQL.noop
        )
    ]
