# Generated by Django 5.2.12 on 2026-05-27 20:38

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_path_is_being_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topology",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                default=None, null=True, spatial_index=False, srid=settings.SRID
            ),
        ),
    ]
