# Generated by Django 5.2.15 on 2026-08-05 16:14

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_drop_pgrouting_node_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgRoutingNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        default=None, null=True, srid=settings.SRID
                    ),
                ),
            ],
        ),
    ]
