# Generated by Django 5.2.15 on 2026-08-05 16:21

from django.core.management import call_command
from django.db import migrations


def generate_pgr_network_topology(apps, schema_editor):
    call_command("generate_pgr_network_topology", "--flush")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_pgroutingnode"),
    ]

    operations = [
        migrations.RunPython(generate_pgr_network_topology, migrations.RunPython.noop),
    ]
