# Generated by Django 5.2.12 on 2026-04-24 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_topology_geom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topology",
            options={
                "permissions": [
                    (
                        "can_draw_off_path_network",
                        "Can draw geometries uncoupled from the path network",
                    )
                ],
                "verbose_name": "Topology",
                "verbose_name_plural": "Topologies",
            },
        ),
    ]
