# Generated by Django 5.2.15 on 2026-08-05 16:21

from django.db import migrations


# This migration used to pre-generate the pgRouting topology graph.
# It is now a no-op, as it will be generated again in the next migration.
class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_pgroutingnode"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
