# Generated by Django 5.2.12 on 2026-04-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_topology_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topology',
            options={'permissions': [('can_draw_on_path_network', 'Can draw geometries coupled to the path network'), ('can_draw_off_path_network', 'Can draw geometries uncoupled from the path network')], 'verbose_name': 'Topology', 'verbose_name_plural': 'Topologies'},
        ),
    ]
