# Generated by Django 5.2.16 on 2026-08-06 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_topology_options"),
        ("core", "0055_pre_generate_pgrouting_graph_topology"),
    ]

    operations = []
