# Generated by Django 5.2.16 on 2026-09-15 13:34

from django.core.management import call_command
from django.db import migrations


def generate_pgr_network_topology(apps, schema_editor):
    call_command("generate_pgr_network_topology", "--flush")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_pre_generate_pgrouting_graph_topology"),
    ]

    operations = [
        migrations.RunPython(generate_pgr_network_topology, migrations.RunPython.noop),
    ]
