# Generated by Django 5.2.16 on 2026-09-22 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_auto_20260915_1334"),
        ("core", "0056_merge_20260806_1605"),
    ]

    operations = []
