# Generated by Django 3.1.3 on 2020-11-26 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0004_auto_20200831_1406"),
    ]

    operations = [
        # Remove point edges
        migrations.RunSQL(
            "DELETE FROM zoning_cityedge USING core_topology WHERE id=topo_object_id AND ST_GeometryType(geom)='ST_Point';"
            "DELETE FROM zoning_districtedge USING core_topology WHERE id=topo_object_id AND ST_GeometryType(geom)='ST_Point';"
            "DELETE FROM zoning_restrictedareaedge USING core_topology WHERE id=topo_object_id AND ST_GeometryType(geom)='ST_Point';",
            migrations.RunSQL.noop,
        )
    ]
