# Generated by Django 3.1.5 on 2021-01-26 09:56

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0006_clean_spatial_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=settings.SRID
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=settings.SRID
            ),
        ),
        migrations.AlterField(
            model_name="restrictedarea",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=settings.SRID
            ),
        ),
    ]
