# Generated by Django 3.1.5 on 2021-01-18 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0007_auto_20210126_0956"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CityEdge",
        ),
        migrations.DeleteModel(
            name="DistrictEdge",
        ),
        migrations.DeleteModel(
            name="RestrictedAreaEdge",
        ),
    ]
