# Generated by Django 3.2.15 on 2022-09-19 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0101_auto_20220913_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Insertion date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Update date"
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Insertion date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="district",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Update date"
            ),
        ),
        migrations.AddField(
            model_name="restrictedarea",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Insertion date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restrictedarea",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Update date"
            ),
        ),
    ]
