# Generated by Django 4.2.20 on 2025-04-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoning', '0103_alter_restrictedarea_area_type'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE zoning_city DROP CONSTRAINT IF EXISTS l_commune_geom_isvalid;
            ALTER TABLE zoning_city DROP CONSTRAINT IF EXISTS zoning_city_geom_isvalid;
            ALTER TABLE zoning_district DROP CONSTRAINT IF EXISTS l_secteur_geom_isvalid;
            ALTER TABLE zoning_district DROP CONSTRAINT IF EXISTS zoning_district_geom_isvalid;
            ALTER TABLE zoning_restrictedarea DROP CONSTRAINT IF EXISTS l_zonage_reglementaire_geom_isvalid;
            ALTER TABLE zoning_restrictedarea DROP CONSTRAINT IF EXISTS zoning_restrictedarea_geom_isvalid;
            """
        )
    ]
