# Generated by Django 4.2.20 on 2025-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0104_auto_20250402_1530"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="city",
            constraint=models.CheckConstraint(
                check=models.Q(("geom__isvalid", True)),
                name="zoning_city_geom_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.CheckConstraint(
                check=models.Q(("geom__isvalid", True)),
                name="zoning_district_geom_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="restrictedarea",
            constraint=models.CheckConstraint(
                check=models.Q(("geom__isvalid", True)),
                name="zoning_restrictedarea_geom_is_valid",
            ),
        ),
    ]
