# Generated by Django 5.2.7 on 2025-10-30 14:40

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0106_auto_20250428_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="envelope",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Envelope(
                    django.contrib.gis.db.models.functions.Transform(
                        "geom", settings.API_SRID
                    )
                ),
                output_field=django.contrib.gis.db.models.fields.GeometryField(
                    srid=4326
                ),
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="envelope",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Envelope(
                    django.contrib.gis.db.models.functions.Transform(
                        "geom", settings.API_SRID
                    )
                ),
                output_field=django.contrib.gis.db.models.fields.GeometryField(
                    srid=4326
                ),
            ),
        ),
        migrations.AddField(
            model_name="restrictedarea",
            name="envelope",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Envelope(
                    django.contrib.gis.db.models.functions.Transform(
                        "geom", settings.API_SRID
                    )
                ),
                output_field=django.contrib.gis.db.models.fields.GeometryField(
                    srid=4326
                ),
            ),
        ),
    ]
