# Generated by Django 5.2.11 on 2026-02-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0108_alter_city_code_alter_city_name_alter_district_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restrictedarea",
            name="name",
            field=models.CharField(db_index=True, max_length=250, verbose_name="Name"),
        ),
        migrations.AddIndex(
            model_name="restrictedarea",
            index=models.Index(
                fields=["area_type_id", "name"], name="restrictedarea_type_name_idx"
            ),
        ),
    ]
