# Generated by Django 5.2.16 on 2026-07-21 15:06

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import mapentity.models
from django.conf import settings
from django.db import migrations, models

import geotrek.authent.models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0011_alter_userprofile_structure"),
        ("common", "0043_alter_targetportal_description_and_more"),
        ("zoning", "0109_alter_restrictedarea_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VigilanceAreaType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pictogram",
                    models.FileField(
                        max_length=512,
                        null=True,
                        upload_to="upload",
                        verbose_name="Pictogram",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Vigilance area type",
                "verbose_name_plural": "Vigilance area types",
            },
        ),
        migrations.CreateModel(
            name="VigilanceArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Visible on Geotrek-rando",
                        verbose_name="Published",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Publication date",
                    ),
                ),
                (
                    "review",
                    models.BooleanField(
                        default=False, verbose_name="Waiting for publication"
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="External id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "practicability",
                    models.CharField(
                        choices=[
                            ("practicable", "Practicable"),
                            ("possibly_practicable", "Possibly practicable"),
                            ("not_practicable", "Not practicable"),
                        ],
                        default="practicable",
                        max_length=50,
                    ),
                ),
                (
                    "practical_info",
                    models.TextField(blank=True, verbose_name="Practical information"),
                ),
                (
                    "external_info_url",
                    models.URLField(
                        blank=True, default="", verbose_name="External information URL"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        spatial_index=False, srid=settings.SRID
                    ),
                ),
                (
                    "portals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vigilance_areas",
                        to="common.targetportal",
                        verbose_name="Portals",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.provider",
                        verbose_name="Provider",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vigilance_areas",
                        to="common.recordsource",
                        verbose_name="Sources",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        default=geotrek.authent.models.default_structure_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
                (
                    "vigilance_area_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vigilance_areas",
                        to="zoning.vigilanceareatype",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigilance area",
                "verbose_name_plural": "Vigilance areas",
                "ordering": ["name"],
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom"], name="vigilance_area_geom_gist_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("geom__isvalid", True)),
                        name="zoning_vigilancearea_geom_is_valid",
                    )
                ],
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
