# Generated by Django 5.2.16 on 2026-07-31 08:19

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
import django.views.generic.dates
import mapentity.models
from django.conf import settings
from django.db import migrations, models

import geotrek.authent.models
import geotrek.common.functions
import geotrek.common.mixins.models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0012_alter_structure_date_insert_and_more"),
        ("common", "0044_alter_accessibilityattachment_date_insert_and_more"),
        ("zoning", "0109_alter_restrictedarea_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VigilanceAreaType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pictogram",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="upload",
                        verbose_name="Pictogram",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Insertion date",
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="Update date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigilance area type",
                "verbose_name_plural": "Vigilance area types",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="restrictedarea",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="restrictedarea",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.CreateModel(
            name="VigilanceArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Insertion date",
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="Update date",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Visible on Geotrek-rando",
                        verbose_name="Published",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Publication date",
                    ),
                ),
                (
                    "review",
                    models.BooleanField(
                        default=False, verbose_name="Waiting for publication"
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="External id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        default=django.views.generic.dates.timezone_today,
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="End date"
                    ),
                ),
                (
                    "practicability",
                    models.CharField(
                        choices=[
                            ("practicable", "Practicable"),
                            (
                                "under_condition_practicable",
                                "Under condition practicable",
                            ),
                            ("not_practicable", "Not practicable"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="practicable",
                        max_length=50,
                        verbose_name="Practicability",
                    ),
                ),
                (
                    "vigilance_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("information", "Information"),
                            ("vigilance", "Vigilance"),
                            ("alert", "Alert"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Vigilance level",
                    ),
                ),
                (
                    "practical_info",
                    models.TextField(blank=True, verbose_name="Practical information"),
                ),
                (
                    "external_info_url",
                    models.URLField(
                        blank=True, default="", verbose_name="External information URL"
                    ),
                ),
                (
                    "active_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (0, "Monday"),
                                (1, "Tuesday"),
                                (2, "Wednesday"),
                                (3, "Thursday"),
                                (4, "Friday"),
                                (5, "Saturday"),
                                (6, "Sunday"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        help_text="Days of the week when the vigilance area is active. Empty equals all week.",
                        size=None,
                        verbose_name="Active days",
                    ),
                ),
                (
                    "active_months",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "January"),
                                (2, "February"),
                                (3, "March"),
                                (4, "April"),
                                (5, "May"),
                                (6, "June"),
                                (7, "July"),
                                (8, "August"),
                                (9, "September"),
                                (10, "October"),
                                (11, "November"),
                                (12, "December"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        help_text="Months of the year when the vigilance area is active. Empty equals all year.",
                        size=None,
                        verbose_name="Active months",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        spatial_index=False, srid=settings.SRID
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_default=geotrek.common.functions.GenRandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "portals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vigilance_areas",
                        to="common.targetportal",
                        verbose_name="Portals",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.provider",
                        verbose_name="Provider",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vigilance_areas",
                        to="common.recordsource",
                        verbose_name="Sources",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        default=geotrek.authent.models.default_structure_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
                (
                    "vigilance_area_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vigilance_areas",
                        to="zoning.vigilanceareatype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "commentary",
                    models.TextField(blank=True, verbose_name="Commentary"),
                ),
            ],
            options={
                "verbose_name": "Vigilance area",
                "verbose_name_plural": "Vigilance areas",
                "ordering": ["name"],
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom"], name="vigilance_area_geom_gist_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["active_days"], name="va_active_days_gin_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["active_months"], name="va_active_months_gin_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("geom__isvalid", True)),
                        name="zoning_vigilancearea_geom_is_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "practicability__in",
                                [
                                    "practicable",
                                    "under_condition_practicable",
                                    "not_practicable",
                                    "closed",
                                ],
                            )
                        ),
                        name="zoning_vigilancearea_practicability_valid",
                    ),
                ],
            },
            bases=(
                mapentity.models.DuplicateMixin,
                geotrek.common.mixins.models.PicturesMixin,
                models.Model,
            ),
        ),
    ]
