# Generated by Django 5.2.16 on 2026-10-09 09:27

import uuid

import colorfield.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
import django.views.generic.dates
import mapentity.models
from django.db import migrations, models

import geotrek.authent.models
import geotrek.common.functions
import geotrek.common.mixins.models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0012_alter_structure_date_insert_and_more"),
        ("common", "0044_alter_accessibilityattachment_date_insert_and_more"),
        ("zoning", "0109_alter_restrictedarea_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VigilanceAreaType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Insertion date",
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="Update date",
                    ),
                ),
                (
                    "pictogram",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="upload",
                        verbose_name="Pictogram",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Vigilance area type",
                "verbose_name_plural": "Vigilance area types",
            },
        ),
        migrations.CreateModel(
            name="VigilanceLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Insertion date",
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="Update date",
                    ),
                ),
                (
                    "pictogram",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="upload",
                        verbose_name="Pictogram",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#1257A8",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Color",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(null=True, unique=True)),
            ],
            options={
                "verbose_name": "Vigilance level",
                "verbose_name_plural": "Vigilance levels",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="restrictedarea",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="restrictedarea",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.CreateModel(
            name="VigilanceArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Insertion date",
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        verbose_name="Update date",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Visible on Geotrek-rando",
                        verbose_name="Published",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Publication date",
                    ),
                ),
                (
                    "review",
                    models.BooleanField(
                        default=False, verbose_name="Waiting for publication"
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="External id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "impracticable",
                    models.BooleanField(default=False, verbose_name="Impracticable"),
                ),
                (
                    "practical_info",
                    models.TextField(blank=True, verbose_name="Practical information"),
                ),
                (
                    "external_info_url",
                    models.URLField(
                        blank=True, default="", verbose_name="External information URL"
                    ),
                ),
                (
                    "private_comment",
                    models.TextField(blank=True, verbose_name="Private comment"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        spatial_index=False, srid=2154
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_default=geotrek.common.functions.GenRandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "portals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vigilance_areas",
                        to="common.targetportal",
                        verbose_name="Portals",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.provider",
                        verbose_name="Provider",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vigilance_areas",
                        to="common.recordsource",
                        verbose_name="Sources",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        default=geotrek.authent.models.default_structure_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
                (
                    "vigilance_area_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vigilance_areas",
                        to="zoning.vigilanceareatype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "vigilance_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vigilance_areas",
                        to="zoning.vigilancelevel",
                        verbose_name="Vigilance level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigilance area",
                "verbose_name_plural": "Vigilance areas",
                "ordering": ["name"],
            },
            bases=(
                mapentity.models.DuplicateMixin,
                geotrek.common.mixins.models.PicturesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VigilancePeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        default=django.views.generic.dates.timezone_today,
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="End date"
                    ),
                ),
                (
                    "active_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (0, "Monday"),
                                (1, "Tuesday"),
                                (2, "Wednesday"),
                                (3, "Thursday"),
                                (4, "Friday"),
                                (5, "Saturday"),
                                (6, "Sunday"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        help_text="Days of the week when the vigilance area is active. Empty equals all week.",
                        size=None,
                        verbose_name="Active days",
                    ),
                ),
                (
                    "annual",
                    models.BooleanField(
                        default=False, verbose_name="Annual recurrence"
                    ),
                ),
                (
                    "vigilance_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="zoning.vigilancearea",
                        verbose_name="Vigilance level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigilance area period",
                "verbose_name_plural": "Vigilance area periods",
                "ordering": ["start_date", "end_date"],
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="vigilancearea",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom"], name="vigilance_area_geom_gist_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vigilancearea",
            constraint=models.CheckConstraint(
                condition=models.Q(("geom__isvalid", True)),
                name="zoning_vigilancearea_geom_is_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="vigilanceperiod",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["active_days"], name="va_active_days_gin_idx"
            ),
        ),
    ]
