# Generated by Django 5.2.16 on 2026-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0110_vigilanceareatype_vigilancearea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vigilancearea",
            name="practicability",
            field=models.CharField(
                choices=[
                    ("practicable", "Practicable"),
                    ("possibly_practicable", "Possibly practicable"),
                    ("not_practicable", "Not practicable"),
                ],
                default="practicable",
                max_length=50,
                verbose_name="Practicability",
            ),
        ),
    ]
