# Generated by Django 5.2.16 on 2026-07-31 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0110_vigilanceareatype_alter_city_date_insert_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP FUNCTION IF EXISTS lien_auto_troncon_couches_sig_d() CASCADE;
            DROP FUNCTION IF EXISTS auto_link_path_topologies_d() CASCADE;
            
            DROP FUNCTION IF EXISTS nettoyage_auto_couches_sig_d() CASCADE;
            DROP FUNCTION IF EXISTS auto_clean_topologies_sig_d() CASCADE;
            
            DROP FUNCTION IF EXISTS lien_auto_troncon_couches_sig_iu() CASCADE;
            DROP FUNCTION IF EXISTS auto_link_path_topologies_iu() CASCADE;
            
            DROP FUNCTION IF EXISTS lien_auto_couches_sig_troncon_iu() CASCADE;
            DROP FUNCTION IF EXISTS auto_link_topologies_path_iu() CASCADE;
            
            DROP VIEW IF EXISTS v_cities CASCADE;
            DROP VIEW IF EXISTS v_districts CASCADE;
            DROP VIEW IF EXISTS v_restrictedareas CASCADE;
            DROP VIEW IF EXISTS v_vigilanceareas CASCADE;
            """
        )
    ]
