# Generated by Django 5.2.16 on 2026-07-23 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0111_alter_vigilancearea_practicability"),
    ]

    operations = [
        migrations.AddField(
            model_name="vigilancearea",
            name="active_days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(verbose_name="Active days"),
                blank=True,
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="vigilancearea",
            name="active_months",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(verbose_name="Active months"),
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=list,
                size=None,
            ),
        ),
    ]
