# Generated by Django 5.2.16 on 2026-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0012_alter_structure_date_insert_and_more"),
        ("common", "0044_alter_accessibilityattachment_date_insert_and_more"),
        ("zoning", "0111_auto_20260731_1045"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vigilancearea",
            name="zoning_vigilancearea_practicability_valid",
        ),
        migrations.AlterField(
            model_name="vigilancearea",
            name="practicability",
            field=models.CharField(
                choices=[
                    ("practicable", "Practicable"),
                    ("under_condition_practicable", "Under condition practicable"),
                    ("not_practicable", "Not practicable"),
                ],
                db_index=True,
                default="practicable",
                max_length=50,
                verbose_name="Practicability",
            ),
        ),
        migrations.AddConstraint(
            model_name="vigilancearea",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "practicability__in",
                        [
                            "practicable",
                            "under_condition_practicable",
                            "not_practicable",
                        ],
                    )
                ),
                name="zoning_vigilancearea_practicability_valid",
            ),
        ),
    ]
