# Generated by Django 5.2.16 on 2026-07-27 12:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0112_vigilancearea_active_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vigilancearea",
            name="active_days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "Monday"),
                        (1, "Tuesday"),
                        (2, "Wednesday"),
                        (3, "Thursday"),
                        (4, "Friday"),
                        (5, "Saturday"),
                        (6, "Sunday"),
                    ]
                ),
                blank=True,
                default=list,
                help_text="Days of the week when the vigilance area is active. Empty equals all week.",
                size=None,
                verbose_name="Active days",
            ),
        ),
        migrations.AlterField(
            model_name="vigilancearea",
            name="active_months",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "January"),
                        (2, "February"),
                        (3, "March"),
                        (4, "April"),
                        (5, "May"),
                        (6, "June"),
                        (7, "July"),
                        (8, "August"),
                        (9, "September"),
                        (10, "October"),
                        (11, "November"),
                        (12, "December"),
                    ]
                ),
                blank=True,
                default=list,
                help_text="Months of the year when the vigilance area is active. Empty equals all year.",
                size=None,
                verbose_name="Active months",
            ),
        ),
    ]
