# Generated by Django 5.2.16 on 2026-07-27 14:58

import uuid

from django.db import migrations, models

import geotrek.common.functions


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0113_alter_vigilancearea_active_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vigilancearea",
            name="uuid",
            field=models.UUIDField(
                db_default=geotrek.common.functions.GenRandomUUID(),
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
