# Generated by Django 5.2.16 on 2026-07-27 17:49

import django.db.models.functions.datetime
import django.views.generic.dates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0114_vigilancearea_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vigilancearea",
            name="start_date",
            field=models.DateField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.views.generic.dates.timezone_today,
                verbose_name="Start date",
            ),
        ),
    ]
