# Generated by Django 5.2.16 on 2026-07-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoning", "0115_alter_vigilancearea_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vigilancearea",
            name="practicability",
            field=models.CharField(
                choices=[
                    ("practicable", "Practicable"),
                    ("partially_practicable", "Partially practicable"),
                    ("not_practicable", "Not practicable"),
                ],
                default="practicable",
                max_length=50,
                verbose_name="Practicability",
            ),
        ),
    ]
