#!/bin/sh -e

# set -x
# export DEBCONF_DEBUG=developer

if [ "$1" = "purge" ]; then
	rm -rf /opt/geotrek-admin/var
	deluser --quiet geotrek || true
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
	rm -f /etc/nginx/sites-available/geotrek.conf
	rm -f /etc/nginx/sites-enabled/geotrek.conf

	# Reload nginx
	if [ -f /etc/init.d/nginx ] ; then
		if which invoke-rc.d > /dev/null ; then
			if invoke-rc.d nginx status > /dev/null 2>&1 ; then
				invoke-rc.d nginx reload 3>/dev/null || true
			fi
		else
			if /etc/init.d/nginx status > /dev/null 2>&1 ; then
				/etc/init.d/nginx reload 3>/dev/null || true
			fi
		fi
	fi
fi

#DEBHELPER#

exit 0
