# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0004_auto_20181127_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='eid',
            field=models.CharField(blank=True, db_column=b'id_externe', max_length=1024, null=True, verbose_name='External id'),
        ),
        migrations.AlterField(
            model_name='service',
            name='eid',
            field=models.CharField(blank=True, db_column=b'id_externe', max_length=1024, null=True, verbose_name='External id'),
        ),
        migrations.AlterField(
            model_name='trek',
            name='eid',
            field=models.CharField(blank=True, db_column=b'id_externe', max_length=1024, null=True, verbose_name='External id'),
        ),
        migrations.AlterField(
            model_name='trek',
            name='eid2',
            field=models.CharField(blank=True, db_column=b'id_externe2', max_length=1024, null=True, verbose_name='Second external id'),
        ),
    ]
