# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0009_auto_20190809_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='on_water',
            field=models.BooleanField(db_column=b'sur_leau', default=False, verbose_name='On water'),
        ),
    ]
