# Generated by Django 2.2.16 on 2020-10-12 14:11
from django.db import migrations


def move_is_park_centered(apps, schema_editor):
    Trek = apps.get_model("trekking", "Trek")
    LabelTrek = apps.get_model("trekking", "LabelTrek")
    is_park_centered = LabelTrek.objects.create()

    for trek in Trek.objects.filter(is_park_centered=True):
        trek.labels.add(is_park_centered.id)


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0018_auto_20201012_1411"),
    ]

    operations = [migrations.RunPython(move_is_park_centered)]
