# Generated by Django 2.2.16 on 2020-10-12 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0019_move_is_park_centered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trek",
            name="is_park_centered",
        ),
    ]
