# Generated by Django 3.1.4 on 2020-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_label"),
        ("trekking", "0022_auto_20201117_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="trek",
            name="labels2",
            field=models.ManyToManyField(
                blank=True,
                related_name="labels2",
                to="common.Label",
                verbose_name="Labels",
            ),
        ),
    ]
