# Generated by Django 3.1.4 on 2020-12-15 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0024_copy_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trek",
            name="labels",
        ),
        migrations.RenameField(
            model_name="trek",
            old_name="labels2",
            new_name="labels",
        ),
    ]
