# Generated by Django 3.1.14 on 2022-01-10 09:18

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0027_auto_20210121_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="trek",
            name="ratings_description",
            field=models.TextField(blank=True, verbose_name="Ratings description"),
        ),
        migrations.CreateModel(
            name="RatingScale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        help_text="Within a practice. Alphabetical order if blank",
                        null=True,
                        verbose_name="Order",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rating_scales",
                        to="trekking.practice",
                        verbose_name="Practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating scale",
                "verbose_name_plural": "Rating scales",
                "ordering": ("practice", "order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pictogram",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="upload",
                        verbose_name="Pictogram",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        help_text="Alphabetical order if blank",
                        null=True,
                        verbose_name="Order",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True, default="", max_length=18, verbose_name="Color"
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ratings",
                        to="trekking.ratingscale",
                        verbose_name="Scale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="trek",
            name="ratings",
            field=models.ManyToManyField(
                blank=True, related_name="sites", to="trekking.Rating"
            ),
        ),
    ]
