# Generated by Django 3.1.14 on 2022-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0027_auto_20210121_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='equipment',
            field=models.TextField(blank=True, help_text='Equipment needed', verbose_name='Equipment'),
        ),
    ]
