# Generated by Django 3.1.14 on 2022-01-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0028_auto_20220110_0918"),
    ]

    operations = [
        migrations.AddField(
            model_name="trek",
            name="equipment",
            field=models.TextField(
                blank=True,
                help_text="Equipment needed, adviced ...",
                verbose_name="Equipment",
            ),
        ),
    ]
