# Generated by Django 3.1.14 on 2022-01-19 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0030_auto_20220118_1106"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Accessibility level",
                "verbose_name_plural": "Accessibility levels",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="trek",
            name="accessibility_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treks",
                to="trekking.accessibilitylevel",
                verbose_name="Accessibility level",
            ),
        ),
    ]
