# Generated by Django 3.1.14 on 2022-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0031_auto_20220119_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='accessibility_advice',
            field=models.TextField(blank=True, help_text='Description of the advice for accessibility', verbose_name='Description advice for accessibility'),
        ),
        migrations.AddField(
            model_name='trek',
            name='accessibility_covering',
            field=models.TextField(blank=True, help_text='Description of the covering for accessibility', verbose_name='Description covering for accessibility'),
        ),
        migrations.AddField(
            model_name='trek',
            name='accessibility_exposure',
            field=models.TextField(blank=True, help_text='Description of the exposure for accessibility', verbose_name='Description exposure for accessibility'),
        ),
        migrations.AddField(
            model_name='trek',
            name='accessibility_signage',
            field=models.TextField(blank=True, help_text='Description of the signage for accessibility', verbose_name='Description signage for accessibility'),
        ),
        migrations.AddField(
            model_name='trek',
            name='accessibility_slope',
            field=models.TextField(blank=True, help_text='Description of the slope for accessibility', verbose_name='Description slope for accessibility'),
        ),
        migrations.AddField(
            model_name='trek',
            name='accessibility_width',
            field=models.TextField(blank=True, help_text='Description of the width for accessibility', verbose_name='Description width for accessibility'),
        ),
    ]
