# Generated by Django 3.1.14 on 2022-01-31 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0033_accessibilityattachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessibilityAttachment",
        ),
    ]
