# Generated by Django 3.1.14 on 2022-02-03 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0034_delete_accessibilityattachment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trek",
            old_name="equipment",
            new_name="gear",
        ),
    ]
