# Generated by Django 3.1.14 on 2022-02-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0035_auto_20220203_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='accessibility_infrastructure',
            field=models.TextField(blank=True, help_text='Any specific accessibility infrastructure', verbose_name='Accessibility infrastructure'),
        ),
    ]
