# Generated by Django 3.1.14 on 2022-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0035_auto_20220203_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trek",
            name="gear",
            field=models.TextField(
                blank=True, help_text="Gear needed, adviced ...", verbose_name="Gear"
            ),
        ),
    ]
