# Generated by Django 3.2.18 on 2023-04-06 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cirkwi", "0003_auto_20200406_1353"),
        ("common", "0030_auto_20230202_1535"),
        ("trekking", "0043_auto_20221110_1128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibility",
            name="cirkwi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cirkwi.cirkwitag",
                verbose_name="Cirkwi tag",
            ),
        ),
        migrations.AlterField(
            model_name="difficultylevel",
            name="cirkwi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cirkwi.cirkwitag",
                verbose_name="Cirkwi tag",
            ),
        ),
        migrations.AlterField(
            model_name="poi",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pois",
                to="trekking.poitype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="poitype",
            name="cirkwi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cirkwi.cirkwipoicategory",
                verbose_name="Cirkwi POI category",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="cirkwi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cirkwi.cirkwilocomotion",
                verbose_name="Cirkwi locomotion",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="trekking.ratingscale",
                verbose_name="Scale",
            ),
        ),
        migrations.AlterField(
            model_name="ratingscale",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating_scales",
                to="trekking.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="trekking.servicetype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="trek",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treks",
                to="trekking.difficultylevel",
                verbose_name="Difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="trek",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treks",
                to="trekking.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="trek",
            name="reservation_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.reservationsystem",
                verbose_name="Reservation system",
            ),
        ),
        migrations.AlterField(
            model_name="trek",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treks",
                to="trekking.route",
                verbose_name="Route",
            ),
        ),
    ]
