# Generated by Django 3.2.18 on 2023-05-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0045_auto_20230407_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='trekking.weblinkcategory', verbose_name='Category'),
        ),
    ]
