# Generated by Django 3.2.19 on 2023-06-07 16:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0046_alter_weblink_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='color',
            field=colorfield.fields.ColorField(default='#444444', help_text='Color of the practice, only used in mobile and pdfs.', image_field=None, max_length=18, samples=None, verbose_name='Color'),
        ),
    ]
