# Generated by Django 3.2.21 on 2023-09-27 15:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0047_remove_servicetype_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practice",
            name="color",
            field=colorfield.fields.ColorField(
                default="#444444",
                help_text="Color of the practice, only used in mobile.",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
