# Generated by Django 3.2.24 on 2024-03-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0047_alter_practice_color'),
        ('trekking', '0048_auto_20230927_1709'),
    ]

    operations = [
    ]
