# Generated by Django 3.2.15 on 2022-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0042_auto_20220907_1253'),
        ('trekking', '0048_auto_20220922_1107'),
    ]

    operations = [
    ]
