# Generated by Django 4.2.10 on 2024-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0048_auto_20230927_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='related_treks',
            field=models.ManyToManyField(help_text='Connections between treks', related_name='related_treks+', through='trekking.TrekRelationship', to='trekking.trek', verbose_name='Related treks'),
        ),
    ]
