# Generated by Django 4.2.21 on 2025-06-11 08:44

import django.db.models.deletion
from django.db import migrations, models


def forward_fill_provider(apps, schema_editor):
    provider_model = apps.get_model('common', 'Provider')

    models = ["Trek", "POI", "Service"]
    for model_name in models:
        model = apps.get_model('trekking', model_name)

        for obj in model.objects.all():
            if obj.provider:
                provider, _ = provider_model.objects.get_or_create(name=obj.provider)
                obj.provider_fk = provider
                obj.save()

def backward_fill_provider(apps, schema_editor):
    models = ["Trek", "POI", "Service"]
    for model_name in models:
        model = apps.get_model('trekking', model_name)

        for obj in model.objects.all():
            if obj.provider_fk:
                obj.provider = obj.provider_fk.name
                obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_provider'),
        ('trekking', '0049_auto_20240417_1519'),
    ]

    operations = [
        # add a new fk field for provider
        migrations.AddField(
            model_name='trek',
            name='provider_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='poi',
            name='provider_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='common.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='common.provider', verbose_name='Provider'),
        ),

        # Populate provider_fk field with provider values
        migrations.RunPython(forward_fill_provider, backward_fill_provider),

        # Delete provider field
        migrations.RemoveField(
            model_name='trek',
            name='provider'
        ),
        migrations.RemoveField(
            model_name='poi',
            name='provider'
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider'
        ),

        # Rename provider_fk field
        migrations.RenameField(
            model_name='trek',
            old_name='provider_fk',
            new_name='provider'
        ),
        migrations.RenameField(
            model_name='poi',
            old_name='provider_fk',
            new_name='provider'
        ),
        migrations.RenameField(
            model_name='service',
            old_name='provider_fk',
            new_name='provider'
        )
    ]
