# Generated by Django 3.2.24 on 2024-03-06 09:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0049_merge_20240306_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='color',
            field=colorfield.fields.ColorField(default='#444444', help_text='Color of the practice, only used in mobile and pdfs.', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
