# Generated by Django 4.2.22 on 2025-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0050_auto_20250611_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poi",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="trek",
            name="eid",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="External id"
            ),
        ),
    ]
