# Generated by Django 5.2.11 on 2026-02-19 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0051_alter_poi_eid_alter_service_eid_alter_trek_eid"),
    ]

    operations = [
        migrations.RunSQL(
            ["DROP FUNCTION IF EXISTS troncons_unpublish_trek_d() CASCADE;"],
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            ["DROP FUNCTION IF EXISTS paths_unpublish_trek_d() CASCADE;"],
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            ["DROP FUNCTION IF EXISTS paths_related_objects_d() CASCADE;"],
            migrations.RunSQL.noop,
        ),
    ]
