# Generated by Django 1.11.27 on 2020-02-11 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_auto_20190306_1417"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportcategory",
            options={
                "ordering": ("category",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelTable(
            name="report",
            table=None,
        ),
        migrations.AlterModelTable(
            name="reportcategory",
            table=None,
        ),
        migrations.AlterModelTable(
            name="reportstatus",
            table=None,
        ),
    ]
