# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_auto_20200228_1755"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="name",
        ),
    ]
