# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_report_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=128, verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('activity',),
            },
        ),
        migrations.CreateModel(
            name='ReportProblemMagnitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.CharField(max_length=128, verbose_name='Problem magnitude')),
            ],
            options={
                'verbose_name': 'Problem magnitude',
                'verbose_name_plural': 'Problem magnitudes',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feedback.ReportActivity', verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='report',
            name='problem_magnitude',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feedback.ReportProblemMagnitude', verbose_name='Problem magnitude'),
        ),
    ]
