# Generated by Django 2.0.13 on 2020-04-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_auto_20200406_1408"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128, verbose_name="Activity")),
                (
                    "suricate_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Suricate id"
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="ReportProblemMagnitude",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=128, verbose_name="Problem magnitude"),
                ),
                (
                    "suricate_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Suricate id"
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem magnitude",
                "verbose_name_plural": "Problem magnitudes",
                "ordering": ("id",),
            },
        ),
        migrations.AlterModelOptions(
            name="reportcategory",
            options={
                "ordering": ("label",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RenameField(
            model_name="reportcategory",
            old_name="category",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="reportstatus",
            old_name="status",
            new_name="label",
        ),
        migrations.AddField(
            model_name="reportcategory",
            name="suricate_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Suricate id"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.ReportCategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.ReportStatus",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.ReportActivity",
                verbose_name="Activity",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="problem_magnitude",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.ReportProblemMagnitude",
                verbose_name="Problem magnitude",
            ),
        ),
    ]
