# Generated by Django 2.2.12 on 2020-05-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0007_auto_20200407_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.ReportActivity",
                verbose_name="Activity",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.ReportCategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="problem_magnitude",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.ReportProblemMagnitude",
                verbose_name="Problem magnitude",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.ReportStatus",
                verbose_name="Status",
            ),
        ),
    ]
