# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20200326_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportactivity',
            options={'ordering': ('label',), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'ordering': ('label',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='reportactivity',
            old_name='activity',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='reportcategory',
            old_name='category',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='reportproblemmagnitude',
            old_name='magnitude',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='reportstatus',
            old_name='status',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='suricate_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Suricate id'),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='suricate_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Suricate id'),
        ),
        migrations.AlterField(
            model_name='reportproblemmagnitude',
            name='suricate_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Suricate id'),
        ),
    ]
