# Generated by Django 2.2.13 on 2020-10-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trekking", "0001_initial"),
        ("feedback", "0009_auto_20200708_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="related_trek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trekking.Trek",
                verbose_name="Related trek",
            ),
        ),
    ]
