# Generated by Django 2.2.13 on 2020-10-12 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0010_report_related_trek"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="context_content_type",
        ),
        migrations.RemoveField(
            model_name="report",
            name="context_object_id",
        ),
    ]
