# Generated by Django 3.1.3 on 2020-11-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0011_auto_20201012_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date d'insertion"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Date de modification"
            ),
        ),
    ]
