# Generated by Django 3.1.13 on 2021-08-03 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_auto_20201117_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 12, 0, tzinfo=utc), verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 12, 0, tzinfo=utc), verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='report',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
        migrations.AddField(
            model_name='report',
            name='origin',
            field=models.CharField(default='unknown', max_length=100, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='report',
            name='uid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Identifiant'),
        ),
        migrations.AddField(
            model_name='reportstatus',
            name='suricate_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_insert',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Insertion date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='suricate_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Suricate id'),
        ),
        migrations.AlterField(
            model_name='reportproblemmagnitude',
            name='suricate_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Suricate id'),
        ),
        migrations.CreateModel(
            name='AttachedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('suricate_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Identifiant')),
                ('type', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.report')),
            ],
        ),
    ]
