# Generated by Django 3.1.13 on 2021-08-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_auto_20210803_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='report',
            name='created_in_suricate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date in Suricate'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_updated_in_suricate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last updated in Suricate'),
        ),
        migrations.AlterField(
            model_name='report',
            name='origin',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Identifier'),
        ),
    ]
