# Generated by Django 3.1.13 on 2021-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_auto_20210804_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='Deleted'),
        ),
    ]
