# Generated by Django 3.1.13 on 2021-12-21 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trekking', '0027_auto_20210121_0943'),
        ('feedback', '0015_reportproblemmagnitude_suricate_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='related_trek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trekking.trek', verbose_name='Related trek'),
        ),
    ]
