# Generated by Django 3.1.13 on 2021-12-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_auto_20211221_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateTimeField()),
                ('date_notification', models.DateTimeField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='feedback.report')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='feedback.reportstatus')),
            ],
        ),
    ]
