# Generated by Django 3.1.13 on 2021-12-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('feedback', '0017_timerevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectableUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='WorkflowManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.selectableuser')),
            ],
            options={
                'verbose_name': 'Workflow Manager',
                'verbose_name_plural': 'Workflow Managers',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='feedback.selectableuser', verbose_name='Supervisor'),
        ),
    ]
