# Generated by Django 3.1.13 on 2021-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_auto_20211229_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uses_timers',
            field=models.BooleanField(default=False, help_text='Launch timers to alert supervisor if report is not being treated on time', verbose_name='Use timers'),
        ),
    ]
