# Generated by Django 3.1.13 on 2022-01-04 12:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_report_uses_timers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatus',
            name='color',
            field=colorfield.fields.ColorField(default='#444444', max_length=18, verbose_name='Color'),
        ),
    ]
