# Generated by Django 3.1.13 on 2022-01-17 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_auto_20220114_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerevent',
            old_name='date_notification',
            new_name='deadline',
        ),
        migrations.AlterField(
            model_name='timerevent',
            name='date_event',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
