# Generated by Django 3.1.13 on 2022-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_auto_20220117_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('subjet', models.CharField(max_length=200)),
                ('message', models.TextField(verbose_name='Message')),
                ('error_message', models.TextField()),
                ('retries', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PendingSuricateAPIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('GET', 'Get Request'), ('POST', 'Post Request')], max_length=4)),
                ('api', models.CharField(choices=[('STA', 'Standard API'), ('MAN', 'Management API')], max_length=3)),
                ('endpoint', models.CharField(max_length=40)),
                ('params', models.JSONField(max_length=300)),
                ('error_message', models.TextField()),
                ('retries', models.IntegerField(default=0)),
            ],
        ),
    ]
