# Generated by Django 3.1.13 on 2022-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0023_pendingemail_pendingsuricateapirequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sync_error',
            field=models.BooleanField(default=False, help_text='Synchronisation with Suricate is currently pending due to connection problems', verbose_name='Synchronisation error'),
        ),
    ]
