# Generated by Django 3.1.13 on 2022-01-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_report_sync_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemail',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.report'),
        ),
    ]
