# Generated by Django 3.1.14 on 2022-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0025_auto_20220125_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='Predefined email')),
                ('text', models.TextField(blank=True, help_text='Mail body', verbose_name='Content')),
            ],
        ),
    ]
