# Generated by Django 3.1.14 on 2022-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0026_predefinedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mail_error',
            field=models.BooleanField(default=False, help_text='A notification email could not be sent. Please contact an administrator', verbose_name='Mail error'),
        ),
    ]
