# Generated by Django 3.1.14 on 2022-03-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0027_report_mail_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='mail_error',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sync_error',
        ),
        migrations.AddField(
            model_name='report',
            name='mail_errors',
            field=models.IntegerField(default=0, help_text='A notification email could not be sent. Please contact an administrator', verbose_name='Mail error'),
        ),
        migrations.AddField(
            model_name='report',
            name='sync_errors',
            field=models.IntegerField(default=0, help_text='Synchronisation with Suricate is currently pending due to connection problems', verbose_name='Synchronisation error'),
        ),
    ]
