# Generated by Django 3.1.14 on 2022-03-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0028_auto_20220316_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uuid',
            field=models.UUIDField(editable=False, verbose_name='Identifier', null=True),
        ),
    ]
