# Generated by Django 3.1.14 on 2022-03-23 13:47

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('feedback', 'report')
    for row in MyModel.objects.all():
        if row.uid:
            row.uuid = row.uid
        else:
            row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0029_auto_20220323_1345'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='report',
            name='uid',
        ),
    ]
