# Generated by Django 3.1.14 on 2022-03-24 09:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0029_auto_20220324_0944"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="external_uuid",
            field=models.UUIDField(
                editable=False, null=True, unique=True, verbose_name="Identifier"
            ),
        ),
    ]
