# Generated by Django 3.1.14 on 2022-03-28 09:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0032_auto_20220328_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
