# Generated by Django 3.2.15 on 2022-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0036_reportstatus_timer_days'),
        ('feedback', '0037_auto_20220922_1109'),
    ]

    operations = [
    ]
