# Generated by Django 3.2.18 on 2023-03-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0043_auto_20221110_1128'),
        ('feedback', '0037_auto_20221110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='related_trek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trekking.trek', verbose_name='Related trek'),
        ),
    ]
