# Generated by Django 3.2.18 on 2023-04-07 08:15

import django.db.models.deletion
from django.db import migrations, models

import geotrek.feedback.models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0038_alter_report_related_trek"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="feedback.reportactivity",
                verbose_name="Activity",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="feedback.reportcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="problem_magnitude",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="feedback.reportproblemmagnitude",
                verbose_name="Problem magnitude",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=geotrek.feedback.models.status_default,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="feedback.reportstatus",
                verbose_name="Status",
            ),
        ),
    ]
