# Generated by Django 4.2.13 on 2024-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0041_alter_pendingemail_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Email"
            ),
        ),
    ]
