# Generated by Django 4.2.13 on 2024-06-19 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0043_report_provider"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE feedback_report ALTER COLUMN external_uuid DROP DEFAULT;"
        )
    ]
