# Generated by Django 4.2.20 on 2025-05-05 08:04
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0044_auto_20240619_0810"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="assigned_user",
            new_name="current_user",
        ),
        migrations.AlterField(
            model_name="report",
            name="current_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_reports",
                to="feedback.selectableuser",
                verbose_name="Current user",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="assigned_handler",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_reports",
                to="feedback.selectableuser",
                verbose_name="Assigned handler",
            ),
        ),
    ]
