# Generated by Django 4.2.20 on 2025-05-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0045_rename_assigned_user_report_current_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="current_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_reports",
                to="feedback.selectableuser",
                verbose_name="Current user",
            ),
        ),
    ]
