# Generated by Django 4.2.20 on 2025-05-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0046_alter_report_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="assigned_handler",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_reports",
                to="feedback.selectableuser",
                verbose_name="Assigned handler",
            ),
        ),
    ]
