# Generated by Django 5.2.16 on 2026-07-31 08:19

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0047_auto_20250611_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="reportactivity",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="reportactivity",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="reportcategory",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="reportcategory",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="reportproblemmagnitude",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="reportproblemmagnitude",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="reportstatus",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="reportstatus",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
    ]
