# Generated by Django 4.2.22 on 2025-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0047_auto_20250611_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='eid',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='External id'),
        ),
    ]
