/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125AuthenticatedRouteImport } from './routes/{-$locale}/_authenticated'
import { Route as Char123LocaleChar125AuthenticatedIndexRouteImport } from './routes/{-$locale}/_authenticated/index'
import { Route as Char123LocaleChar125AuthenticatedSettingsRouteImport } from './routes/{-$locale}/_authenticated/settings'
import { Route as Char123LocaleChar125AuthenticatedCreateRouteImport } from './routes/{-$locale}/_authenticated/create'
import { Route as Char123LocaleChar125AuthenticatedSyncIndexRouteImport } from './routes/{-$locale}/_authenticated/sync/index'
import { Route as Char123LocaleChar125AuthenticatedSyncMapRouteImport } from './routes/{-$locale}/_authenticated/sync/map'
import { Route as Char123LocaleChar125AuthenticatedSyncDataRouteImport } from './routes/{-$locale}/_authenticated/sync/data'
import { Route as Char123LocaleChar125AuthenticatedDataTypeCreateRouteImport } from './routes/{-$locale}/_authenticated/data/$type/create'
import { Route as Char123LocaleChar125AuthenticatedDataTypeIdIndexRouteImport } from './routes/{-$locale}/_authenticated/data/$type/$id/index'
import { Route as Char123LocaleChar125AuthenticatedDataTypeIdEditRouteImport } from './routes/{-$locale}/_authenticated/data/$type/$id/edit'

const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/{-$locale}/login',
    path: '/{-$locale}/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthenticatedRoute =
  Char123LocaleChar125AuthenticatedRouteImport.update({
    id: '/{-$locale}/_authenticated',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthenticatedIndexRoute =
  Char123LocaleChar125AuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedSettingsRoute =
  Char123LocaleChar125AuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedCreateRoute =
  Char123LocaleChar125AuthenticatedCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedSyncIndexRoute =
  Char123LocaleChar125AuthenticatedSyncIndexRouteImport.update({
    id: '/sync/',
    path: '/sync/',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedSyncMapRoute =
  Char123LocaleChar125AuthenticatedSyncMapRouteImport.update({
    id: '/sync/map',
    path: '/sync/map',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedSyncDataRoute =
  Char123LocaleChar125AuthenticatedSyncDataRouteImport.update({
    id: '/sync/data',
    path: '/sync/data',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedDataTypeCreateRoute =
  Char123LocaleChar125AuthenticatedDataTypeCreateRouteImport.update({
    id: '/data/$type/create',
    path: '/data/$type/create',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute =
  Char123LocaleChar125AuthenticatedDataTypeIdIndexRouteImport.update({
    id: '/data/$type/$id/',
    path: '/data/$type/$id/',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedDataTypeIdEditRoute =
  Char123LocaleChar125AuthenticatedDataTypeIdEditRouteImport.update({
    id: '/data/$type/$id/edit',
    path: '/data/$type/$id/edit',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125AuthenticatedRouteWithChildren
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/create': typeof Char123LocaleChar125AuthenticatedCreateRoute
  '/{-$locale}/settings': typeof Char123LocaleChar125AuthenticatedSettingsRoute
  '/{-$locale}/': typeof Char123LocaleChar125AuthenticatedIndexRoute
  '/{-$locale}/sync/data': typeof Char123LocaleChar125AuthenticatedSyncDataRoute
  '/{-$locale}/sync/map': typeof Char123LocaleChar125AuthenticatedSyncMapRoute
  '/{-$locale}/sync/': typeof Char123LocaleChar125AuthenticatedSyncIndexRoute
  '/{-$locale}/data/$type/create': typeof Char123LocaleChar125AuthenticatedDataTypeCreateRoute
  '/{-$locale}/data/$type/$id/edit': typeof Char123LocaleChar125AuthenticatedDataTypeIdEditRoute
  '/{-$locale}/data/$type/$id/': typeof Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/create': typeof Char123LocaleChar125AuthenticatedCreateRoute
  '/{-$locale}/settings': typeof Char123LocaleChar125AuthenticatedSettingsRoute
  '/{-$locale}': typeof Char123LocaleChar125AuthenticatedIndexRoute
  '/{-$locale}/sync/data': typeof Char123LocaleChar125AuthenticatedSyncDataRoute
  '/{-$locale}/sync/map': typeof Char123LocaleChar125AuthenticatedSyncMapRoute
  '/{-$locale}/sync': typeof Char123LocaleChar125AuthenticatedSyncIndexRoute
  '/{-$locale}/data/$type/create': typeof Char123LocaleChar125AuthenticatedDataTypeCreateRoute
  '/{-$locale}/data/$type/$id/edit': typeof Char123LocaleChar125AuthenticatedDataTypeIdEditRoute
  '/{-$locale}/data/$type/$id': typeof Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/_authenticated': typeof Char123LocaleChar125AuthenticatedRouteWithChildren
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/_authenticated/create': typeof Char123LocaleChar125AuthenticatedCreateRoute
  '/{-$locale}/_authenticated/settings': typeof Char123LocaleChar125AuthenticatedSettingsRoute
  '/{-$locale}/_authenticated/': typeof Char123LocaleChar125AuthenticatedIndexRoute
  '/{-$locale}/_authenticated/sync/data': typeof Char123LocaleChar125AuthenticatedSyncDataRoute
  '/{-$locale}/_authenticated/sync/map': typeof Char123LocaleChar125AuthenticatedSyncMapRoute
  '/{-$locale}/_authenticated/sync/': typeof Char123LocaleChar125AuthenticatedSyncIndexRoute
  '/{-$locale}/_authenticated/data/$type/create': typeof Char123LocaleChar125AuthenticatedDataTypeCreateRoute
  '/{-$locale}/_authenticated/data/$type/$id/edit': typeof Char123LocaleChar125AuthenticatedDataTypeIdEditRoute
  '/{-$locale}/_authenticated/data/$type/$id/': typeof Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/login'
    | '/{-$locale}/create'
    | '/{-$locale}/settings'
    | '/{-$locale}/'
    | '/{-$locale}/sync/data'
    | '/{-$locale}/sync/map'
    | '/{-$locale}/sync/'
    | '/{-$locale}/data/$type/create'
    | '/{-$locale}/data/$type/$id/edit'
    | '/{-$locale}/data/$type/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/login'
    | '/{-$locale}/create'
    | '/{-$locale}/settings'
    | '/{-$locale}'
    | '/{-$locale}/sync/data'
    | '/{-$locale}/sync/map'
    | '/{-$locale}/sync'
    | '/{-$locale}/data/$type/create'
    | '/{-$locale}/data/$type/$id/edit'
    | '/{-$locale}/data/$type/$id'
  id:
    | '__root__'
    | '/{-$locale}/_authenticated'
    | '/{-$locale}/login'
    | '/{-$locale}/_authenticated/create'
    | '/{-$locale}/_authenticated/settings'
    | '/{-$locale}/_authenticated/'
    | '/{-$locale}/_authenticated/sync/data'
    | '/{-$locale}/_authenticated/sync/map'
    | '/{-$locale}/_authenticated/sync/'
    | '/{-$locale}/_authenticated/data/$type/create'
    | '/{-$locale}/_authenticated/data/$type/$id/edit'
    | '/{-$locale}/_authenticated/data/$type/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125AuthenticatedRoute: typeof Char123LocaleChar125AuthenticatedRouteWithChildren
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/{-$locale}/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_authenticated': {
      id: '/{-$locale}/_authenticated'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_authenticated/': {
      id: '/{-$locale}/_authenticated/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/settings': {
      id: '/{-$locale}/_authenticated/settings'
      path: '/settings'
      fullPath: '/{-$locale}/settings'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/create': {
      id: '/{-$locale}/_authenticated/create'
      path: '/create'
      fullPath: '/{-$locale}/create'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedCreateRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/sync/': {
      id: '/{-$locale}/_authenticated/sync/'
      path: '/sync'
      fullPath: '/{-$locale}/sync/'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedSyncIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/sync/map': {
      id: '/{-$locale}/_authenticated/sync/map'
      path: '/sync/map'
      fullPath: '/{-$locale}/sync/map'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedSyncMapRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/sync/data': {
      id: '/{-$locale}/_authenticated/sync/data'
      path: '/sync/data'
      fullPath: '/{-$locale}/sync/data'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedSyncDataRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/data/$type/create': {
      id: '/{-$locale}/_authenticated/data/$type/create'
      path: '/data/$type/create'
      fullPath: '/{-$locale}/data/$type/create'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedDataTypeCreateRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/data/$type/$id/': {
      id: '/{-$locale}/_authenticated/data/$type/$id/'
      path: '/data/$type/$id'
      fullPath: '/{-$locale}/data/$type/$id/'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedDataTypeIdIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/data/$type/$id/edit': {
      id: '/{-$locale}/_authenticated/data/$type/$id/edit'
      path: '/data/$type/$id/edit'
      fullPath: '/{-$locale}/data/$type/$id/edit'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedDataTypeIdEditRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
  }
}

interface Char123LocaleChar125AuthenticatedRouteChildren {
  Char123LocaleChar125AuthenticatedCreateRoute: typeof Char123LocaleChar125AuthenticatedCreateRoute
  Char123LocaleChar125AuthenticatedSettingsRoute: typeof Char123LocaleChar125AuthenticatedSettingsRoute
  Char123LocaleChar125AuthenticatedIndexRoute: typeof Char123LocaleChar125AuthenticatedIndexRoute
  Char123LocaleChar125AuthenticatedSyncDataRoute: typeof Char123LocaleChar125AuthenticatedSyncDataRoute
  Char123LocaleChar125AuthenticatedSyncMapRoute: typeof Char123LocaleChar125AuthenticatedSyncMapRoute
  Char123LocaleChar125AuthenticatedSyncIndexRoute: typeof Char123LocaleChar125AuthenticatedSyncIndexRoute
  Char123LocaleChar125AuthenticatedDataTypeCreateRoute: typeof Char123LocaleChar125AuthenticatedDataTypeCreateRoute
  Char123LocaleChar125AuthenticatedDataTypeIdEditRoute: typeof Char123LocaleChar125AuthenticatedDataTypeIdEditRoute
  Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute: typeof Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute
}

const Char123LocaleChar125AuthenticatedRouteChildren: Char123LocaleChar125AuthenticatedRouteChildren =
  {
    Char123LocaleChar125AuthenticatedCreateRoute:
      Char123LocaleChar125AuthenticatedCreateRoute,
    Char123LocaleChar125AuthenticatedSettingsRoute:
      Char123LocaleChar125AuthenticatedSettingsRoute,
    Char123LocaleChar125AuthenticatedIndexRoute:
      Char123LocaleChar125AuthenticatedIndexRoute,
    Char123LocaleChar125AuthenticatedSyncDataRoute:
      Char123LocaleChar125AuthenticatedSyncDataRoute,
    Char123LocaleChar125AuthenticatedSyncMapRoute:
      Char123LocaleChar125AuthenticatedSyncMapRoute,
    Char123LocaleChar125AuthenticatedSyncIndexRoute:
      Char123LocaleChar125AuthenticatedSyncIndexRoute,
    Char123LocaleChar125AuthenticatedDataTypeCreateRoute:
      Char123LocaleChar125AuthenticatedDataTypeCreateRoute,
    Char123LocaleChar125AuthenticatedDataTypeIdEditRoute:
      Char123LocaleChar125AuthenticatedDataTypeIdEditRoute,
    Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute:
      Char123LocaleChar125AuthenticatedDataTypeIdIndexRoute,
  }

const Char123LocaleChar125AuthenticatedRouteWithChildren =
  Char123LocaleChar125AuthenticatedRoute._addFileChildren(
    Char123LocaleChar125AuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125AuthenticatedRoute:
    Char123LocaleChar125AuthenticatedRouteWithChildren,
  Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
