# Generated by Django 1.11.14 on 2020-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flatpages", "0003_auto_20200211_1011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatpage",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Insertion date"
            ),
        ),
        migrations.AlterField(
            model_name="flatpage",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Update date"
            ),
        ),
        migrations.AlterField(
            model_name="flatpage",
            name="publication_date",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Publication date"
            ),
        ),
        migrations.AlterField(
            model_name="flatpage",
            name="published",
            field=models.BooleanField(
                default=False, help_text="Online", verbose_name="Published"
            ),
        ),
    ]
