# Generated by Django 3.2.23 on 2024-02-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_accessmean'),
        ('flatpages', '0009_auto_20210121_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Insertion date')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('content_type', models.CharField(choices=[('Page', 'Page'), ('Link', 'Link')], max_length=10, null=True)),
                ('link_url', models.URLField(blank=True, default='', verbose_name='Link URL')),
                ('target', models.CharField(choices=[('all', 'All'), ('mobile', 'Mobile'), ('hidden', 'Hidden'), ('web', 'Web')], default='all', max_length=12, verbose_name='Target')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.flatpage')),
                ('portal', models.ManyToManyField(blank=True, related_name='menu_items', to='common.TargetPortal', verbose_name='Portal')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
            },
        ),
    ]
