# Generated by Django 3.2.23 on 2024-02-16 15:11

from django.db import migrations, models


def set_treebeard_path_fields(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    pages = FlatPage.objects.all()
    for page in pages:
        page.path = str(page.pk)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0010_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpage',
            options={'ordering': ['id'], 'permissions': (('read_flatpage', 'Can read FlatPage'),), 'verbose_name': 'Flat page', 'verbose_name_plural': 'Flat pages'},
        ),
        migrations.RemoveField(
            model_name='flatpage',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='flatpage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='flatpage',
            name='target',
        ),
        migrations.AddField(
            model_name='flatpage',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatpage',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='path',
            field=models.CharField(default=0, max_length=255, unique=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='publication_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='published',
            field=models.BooleanField(default=False, help_text='Visible on Geotrek-rando', verbose_name='Published'),
        ),
        migrations.RunPython(set_treebeard_path_fields),
        migrations.AlterField(
            model_name='flatpage',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
