# Generated by Django 3.2.23 on 2024-02-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0011_auto_20240216_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpage',
            old_name='portal',
            new_name='portals',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='portal',
            new_name='portals',
        ),
    ]
