# Generated by Django 3.2.24 on 2024-03-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0012_change_flatpage_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target_type',
            field=models.CharField(blank=True, choices=[('page', 'Page'), ('link', 'Link')], max_length=10, null=True),
        ),
    ]
