# Generated by Django 3.2.23 on 2024-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0012_auto_20240216_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='content_type',
            new_name='target_type',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='target',
            new_name='platform',
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="target_type",
            field=models.CharField(choices=[('Page', 'page'), ('Link', 'link')], max_length=10, null=True),
        ),
    ]
