# Generated by Django 3.2.23 on 2024-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0013_auto_20240227_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='platform',
            field=models.CharField(choices=[('all', 'All'), ('mobile', 'Mobile'), ('web', 'Web')], default='all', max_length=12, verbose_name='Platform'),
        ),
    ]
