# Generated by Django 3.2.23 on 2024-03-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0014_alter_menuitem_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open the link in a new tab'),
        ),
    ]
