# Generated by Django 3.2.23 on 2024-03-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0015_menuitem_open_in_new_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='pictogram',
            field=models.FileField(max_length=512, null=True, upload_to='upload', verbose_name='Pictogram'),
        ),
    ]
