# Generated by Django 3.2.23 on 2024-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0016_menuitem_pictogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='pictogram',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='upload', verbose_name='Pictogram'),
        ),
    ]
