# Generated by Django 5.2.16 on 2026-07-31 08:19

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flatpages", "0016_alter_flatpage_content_alter_menuitem_target_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatpage",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="flatpage",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="Insertion date",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="Update date",
            ),
        ),
    ]
