# Generated by Django 3.2.23 on 2024-03-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0017_alter_menuitem_pictogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='flatpages.flatpage'),
        ),
    ]
