# Generated by Django 3.2.23 on 2024-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0018_alter_menuitem_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpage',
            options={'permissions': (('read_flatpage', 'Can read FlatPage'),), 'verbose_name': 'Flat page', 'verbose_name_plural': 'Flat pages'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target_type',
            field=models.CharField(choices=[('page', 'Page'), ('link', 'Link')], max_length=10, null=True),
        ),
    ]
