# Generated by Django 3.2.23 on 2024-03-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0019_auto_20240314_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='position',
        ),
    ]
