# Generated by Django 3.2.24 on 2024-03-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("flatpages", "0001_initial"),
        ("flatpages", "0002_auto_20190306_1417"),
        ("flatpages", "0003_auto_20200211_1011"),
        ("flatpages", "0004_auto_20200228_1755"),
        ("flatpages", "0005_auto_20200228_2150"),
        ("flatpages", "0006_auto_20200406_1413"),
        ("flatpages", "0007_auto_20200831_1406"),
        ("flatpages", "0008_auto_20201117_1302"),
        ("flatpages", "0009_auto_20210121_0943"),
    ]
    initial = True

    dependencies = [
        ("common", "0100_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Update date"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Visible on Geotrek-rando",
                        verbose_name="Published",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Publication date",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to external website instead of HTML content",
                        verbose_name="External URL",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="HTML content",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("mobile", "Mobile"),
                            ("hidden", "Hidden"),
                            ("web", "Web"),
                        ],
                        default="all",
                        max_length=12,
                        verbose_name="Target",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="ID order if blank",
                        null=True,
                        verbose_name="Order",
                    ),
                ),
                (
                    "portal",
                    models.ManyToManyField(
                        blank=True,
                        related_name="flatpages",
                        to="common.TargetPortal",
                        verbose_name="Portal",
                    ),
                ),
                (
                    "source",
                    models.ManyToManyField(
                        blank=True,
                        related_name="flatpages",
                        to="common.RecordSource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flat page",
                "verbose_name_plural": "Flat pages",
                "ordering": ["order", "id"],
                "permissions": (("read_flatpage", "Can read FlatPage"),),
            },
        ),
    ]
