# Generated by Django 1.11.14 on 2020-03-02 06:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diving", "0002_auto_20200211_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="difficulty",
            name="pictogram",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="upload",
                verbose_name="Pictogram",
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="advice",
            field=models.TextField(
                blank=True,
                help_text="Risques, danger, meilleure période, ...",
                verbose_name="Recommandation",
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="date_insert",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Insertion date"
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Update date"
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="name",
            field=models.CharField(
                help_text="Public name (Change carefully)",
                max_length=128,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="publication_date",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Publication date"
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="published",
            field=models.BooleanField(
                default=False, help_text="Online", verbose_name="Published"
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="review",
            field=models.BooleanField(
                default=False, verbose_name="Waiting for publication"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="pictogram",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="upload",
                verbose_name="Pictogram",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="color",
            field=colorfield.fields.ColorField(
                default="#444444",
                help_text="Couleur de la pratique, utilisé uniquement pour l'app mobile",
                max_length=18,
                verbose_name="Couleur",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="pictogram",
            field=models.FileField(
                max_length=512, null=True, upload_to="upload", verbose_name="Pictogram"
            ),
        ),
    ]
