# Generated by Django 3.2.18 on 2023-04-07 08:15

import django.db.models.deletion
from django.db import migrations, models

import geotrek.authent.models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0011_alter_userprofile_structure"),
        ("diving", "0007_auto_20221118_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dive",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dives",
                to="diving.difficulty",
                verbose_name="Difficulty level",
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dives",
                to="diving.practice",
                verbose_name="Practice",
            ),
        ),
        migrations.AlterField(
            model_name="dive",
            name="structure",
            field=models.ForeignKey(
                default=geotrek.authent.models.default_structure_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="authent.structure",
                verbose_name="Related structure",
            ),
        ),
    ]
