# Generated by Django 3.1.14 on 2022-09-07 12:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220728_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, null=True, spatial_index=False, srid=2154),
        ),
    ]
