# Generated by Django 1.11.14 on 2018-12-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("land", "0003_auto_20181218_1601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competenceedge",
            name="eid",
            field=models.CharField(
                blank=True,
                db_column="id_externe",
                max_length=1024,
                null=True,
                verbose_name="External id",
            ),
        ),
        migrations.AlterField(
            model_name="landedge",
            name="eid",
            field=models.CharField(
                blank=True,
                db_column="id_externe",
                max_length=1024,
                null=True,
                verbose_name="External id",
            ),
        ),
        migrations.AlterField(
            model_name="physicaledge",
            name="eid",
            field=models.CharField(
                blank=True,
                db_column="id_externe",
                max_length=1024,
                null=True,
                verbose_name="External id",
            ),
        ),
        migrations.AlterField(
            model_name="signagemanagementedge",
            name="eid",
            field=models.CharField(
                blank=True,
                db_column="id_externe",
                max_length=1024,
                null=True,
                verbose_name="External id",
            ),
        ),
        migrations.AlterField(
            model_name="workmanagementedge",
            name="eid",
            field=models.CharField(
                blank=True,
                db_column="id_externe",
                max_length=1024,
                null=True,
                verbose_name="External id",
            ),
        ),
    ]
