# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-10-29 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_auto_20181219_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtype',
            name='structure',
            field=models.ForeignKey(blank=True, db_column=b'structure', null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.Structure', verbose_name='Related structure'),
        ),
        migrations.AlterField(
            model_name='physicaltype',
            name='structure',
            field=models.ForeignKey(blank=True, db_column=b'structure', null=True, on_delete=django.db.models.deletion.CASCADE, to='authent.Structure', verbose_name='Related structure'),
        ),
    ]
