# Generated by Django 1.11.14 on 2019-10-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("land", "0004_auto_20181219_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landtype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="physicaltype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                db_column="structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
    ]
