# Generated by Django 1.11.27 on 2020-02-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("land", "0005_auto_20191029_1110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competenceedge",
            name="eid",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="competenceedge",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.Organism",
                verbose_name="Organism",
            ),
        ),
        migrations.AlterField(
            model_name="competenceedge",
            name="topo_object",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.Topology",
            ),
        ),
        migrations.AlterField(
            model_name="landedge",
            name="agreement",
            field=models.BooleanField(default=False, verbose_name="Agreement"),
        ),
        migrations.AlterField(
            model_name="landedge",
            name="eid",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="landedge",
            name="land_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="land.LandType",
                verbose_name="Land type",
            ),
        ),
        migrations.AlterField(
            model_name="landedge",
            name="owner",
            field=models.TextField(blank=True, verbose_name="Owner"),
        ),
        migrations.AlterField(
            model_name="landedge",
            name="topo_object",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.Topology",
            ),
        ),
        migrations.AlterField(
            model_name="landtype",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="landtype",
            name="right_of_way",
            field=models.BooleanField(default=False, verbose_name="Right of way"),
        ),
        migrations.AlterField(
            model_name="landtype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="physicaledge",
            name="eid",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="physicaledge",
            name="physical_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="land.PhysicalType",
                verbose_name="Physical type",
            ),
        ),
        migrations.AlterField(
            model_name="physicaledge",
            name="topo_object",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.Topology",
            ),
        ),
        migrations.AlterField(
            model_name="physicaltype",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="physicaltype",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authent.Structure",
                verbose_name="Related structure",
            ),
        ),
        migrations.AlterField(
            model_name="signagemanagementedge",
            name="eid",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="signagemanagementedge",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.Organism",
                verbose_name="Organism",
            ),
        ),
        migrations.AlterField(
            model_name="signagemanagementedge",
            name="topo_object",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.Topology",
            ),
        ),
        migrations.AlterField(
            model_name="workmanagementedge",
            name="eid",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="workmanagementedge",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.Organism",
                verbose_name="Organism",
            ),
        ),
        migrations.AlterField(
            model_name="workmanagementedge",
            name="topo_object",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.Topology",
            ),
        ),
        migrations.AlterModelTable(
            name="competenceedge",
            table=None,
        ),
        migrations.AlterModelTable(
            name="landedge",
            table=None,
        ),
        migrations.AlterModelTable(
            name="landtype",
            table=None,
        ),
        migrations.AlterModelTable(
            name="physicaledge",
            table=None,
        ),
        migrations.AlterModelTable(
            name="physicaltype",
            table=None,
        ),
        migrations.AlterModelTable(
            name="signagemanagementedge",
            table=None,
        ),
        migrations.AlterModelTable(
            name="workmanagementedge",
            table=None,
        ),
    ]
