# Generated by Django 3.2.19 on 2023-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0010_auto_20230503_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='landedge',
            name='identification',
            field=models.CharField(blank=True, max_length=40, verbose_name='Land id'),
        ),
    ]
