# Generated by Django 3.2.20 on 2023-08-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0011_circulationedge_circulationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationedge',
            name='authorized',
            field=models.BooleanField(null=True, verbose_name='Authorized'),
        ),
    ]
