# Generated by Django 3.2.20 on 2023-08-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0012_alter_circulationedge_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationedge',
            name='eid',
            field=models.CharField(blank=True, default=5, max_length=1024, verbose_name='External id'),
            preserve_default=False,
        ),
    ]
