# Generated by Django 3.2.20 on 2023-08-31 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0011_alter_userprofile_structure'),
        ('land', '0013_alter_circulationedge_eid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulationedge',
            name='authorized',
        ),
        migrations.CreateModel(
            name='AuthorizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authent.structure', verbose_name='Related structure')),
            ],
            options={
                'verbose_name': 'Authorization type',
                'verbose_name_plural': 'Authorization types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='circulationedge',
            name='authorization_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='land.authorizationtype', verbose_name='Authorization type'),
            preserve_default=False,
        ),
    ]
