# Generated by Django 3.2.24 on 2024-03-08 11:23

from django.db import migrations, models
import django.db.models.deletion
import mapentity.models


class Migration(migrations.Migration):
    replaces = [
        ("land", "0001_initial"),
        ("land", "0002_auto_20180608_1236"),
        ("land", "0003_auto_20181218_1601"),
        ("land", "0004_auto_20181219_1524"),
        ("land", "0005_auto_20191029_1110"),
        ("land", "0006_auto_20200211_1011"),
        ("land", "0007_auto_20200406_1410"),
        ("land", "0008_status"),
        ("land", "0009_auto_20230407_0947"),
        ("land", "0010_auto_20230503_0837"),
        ("land", "0011_authorizationtype_circulationedge_circulationtype"),
    ]
    initial = True

    dependencies = [
        ("common", "0100_initial"),
        ("authent", "0100_initial"),
        ("core", "0100_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorization type",
                "verbose_name_plural": "Authorization types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WorkManagementEdge",
            fields=[
                (
                    "topo_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.topology",
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="External id",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.organism",
                        verbose_name="Organism",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work management edge",
                "verbose_name_plural": "Work management edges",
            },
            bases=(mapentity.models.DuplicateMixin, "core.topology", models.Model),
        ),
        migrations.CreateModel(
            name="SignageManagementEdge",
            fields=[
                (
                    "topo_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.topology",
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="External id",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.organism",
                        verbose_name="Organism",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signage management edge",
                "verbose_name_plural": "Signage management edges",
            },
            bases=(mapentity.models.DuplicateMixin, "core.topology", models.Model),
        ),
        migrations.CreateModel(
            name="PhysicalType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical type",
                "verbose_name_plural": "Physical types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PhysicalEdge",
            fields=[
                (
                    "topo_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.topology",
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="External id",
                    ),
                ),
                (
                    "physical_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="land.physicaltype",
                        verbose_name="Physical type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical edge",
                "verbose_name_plural": "Physical edges",
            },
            bases=(mapentity.models.DuplicateMixin, "core.topology", models.Model),
        ),
        migrations.CreateModel(
            name="LandType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "right_of_way",
                    models.BooleanField(default=False, verbose_name="Right of way"),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land type",
                "verbose_name_plural": "Land types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LandEdge",
            fields=[
                (
                    "topo_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.topology",
                    ),
                ),
                ("owner", models.TextField(blank=True, verbose_name="Owner")),
                (
                    "agreement",
                    models.BooleanField(default=False, verbose_name="Agreement"),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="External id",
                    ),
                ),
                (
                    "land_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="land.landtype",
                        verbose_name="Land type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land edge",
                "verbose_name_plural": "Land edges",
            },
            bases=(mapentity.models.DuplicateMixin, "core.topology", models.Model),
        ),
        migrations.CreateModel(
            name="CompetenceEdge",
            fields=[
                (
                    "topo_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.topology",
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="External id",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.organism",
                        verbose_name="Organism",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competence edge",
                "verbose_name_plural": "Competence edges",
            },
            bases=(mapentity.models.DuplicateMixin, "core.topology", models.Model),
        ),
        migrations.CreateModel(
            name="CirculationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="authent.structure",
                        verbose_name="Related structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Circulation type",
                "verbose_name_plural": "Circulation types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CirculationEdge",
            fields=[
                (
                    "topo_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.topology",
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="External id"
                    ),
                ),
                (
                    "authorization_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="land.authorizationtype",
                        verbose_name="Authorization type",
                    ),
                ),
                (
                    "circulation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="land.circulationtype",
                        verbose_name="Circulation type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Circulation edge",
                "verbose_name_plural": "Circulation edges",
            },
            bases=(mapentity.models.DuplicateMixin, "core.topology", models.Model),
        ),
    ]
