name: frontend.yml
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'frontend/**'  # only if frontend code change
      - '.github/workflows/frontend.yml'  # if lint workflow change

jobs:
  frontend:
    name: Frontend quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get frontend git cache key
        run: |
          echo "FRONTEND_CACHE_KEY=$(git --no-pager log -1 --format="%H" -- frontend/)" >> $GITHUB_ENV
    
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
    
      - name: Cache frontend
        id: cache-frontend
        uses: actions/cache@v6
        with:
          path: ./frontend/dist
          key: frontend-${{ env.FRONTEND_CACHE_KEY }}
    
      - name: Setup node for frontend
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        uses: actions/setup-node@v6
        with:
          node-version-file: './frontend/.nvmrc'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
    
      - name: Install frontend dependencies
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: |
          npm ci --no-audit
    
      - name: Build frontend
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: |
          cp .env.dist .env
          sed -i 's|HOST_URL=.*|HOST_URL=/|' .env
          npm run build
    
      - name: Lint frontend
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: |
          npm run lint
