name: Realese process

on:
  workflow_run:
    workflows: ["Test CI"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Publish
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Prepare release
        run: |
          echo "Preparing release ${{ github.event.inputs.version }}"
          make release version=${{ github.event.inputs.version }}
      - name: commit changes
        run: |
          git config --local user.email "
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Release ${{ github.event.inputs.version }}"

      #- name: Make release
      #  uses: ncipollo/release-action@v1
      #  with:
      #    tag: ${{ github.event.inputs.version }}
      #    name: Release ${{ github.event.inputs.version }}
